### ISSUE TITLE
在MacBook pro双显示器上不能运行

### ISSUE THREAD

**Issue by zhouhesheng** [xzhih/one-key-hidpi#11]
(1) Enable HIDPI
(2) Enable HIDPI (with patch)
(3) Disable HIDPI

Enter your choice [1~3]: 1
------------------------------------
|********** Choose Icon ***********|
------------------------------------
(1) iMac
(2) MacBook
(3) MacBook Pro
(4) LG Display
(5) Remain as it is

Enter your choice [1~5]: 3
sed: 1: "s/VID/610
10ac/g": unescaped newline inside substitute pattern
sed: 1: "s/PID/a040
4080/g": unescaped newline inside substitute pattern
sh: line 113: ./tmp/DisplayVendorID-610
10ac/DisplayProductID-a040
4080: No such file or directory
------------------------------------------
|********** resolution config ***********|
------------------------------------------
(1) 1080P Display
(2) 2K Display
(3) Manual input resolution

Enter your choice:

**Comment by xzhih** [comment]
盒盖运行脚本，这样就能为外置的显示器开启HIDPI了

**Comment by zhouhesheng** [comment]
这个方法还真行，能把我的第二显示器增加了新的
hidpi分辨率。
就是用的时候盒盖要用外接键盘太麻烦，考虑到白苹果用这个主要是改第二显示器的分辨率，作者能否改下scripts加入选择显示器？
谢谢！

**Comment by xzhih** [comment]
嗯，有空我试试吧，放假回家先，现在身边没外显

**Comment by xzhih** [comment]
已添加外置屏幕选择
