### ISSUE TITLE
在小米笔记本PRO的黑苹果上要关机或睡眠时会花屏几秒

### ISSUE THREAD

**Issue by wucheng139** [xzhih/one-key-hidpi#110]
有时也会变小。只占据屏幕的左上角。当然开机后又是正常的。只不过在要关机时有那么几秒的异常。

**Comment by stevezhengshiqi** [comment]
@wucheng139 分辨率选择错误，10.15请选择`(2) 1920x1080 显示屏 (使用 1424x802 分辨率，修复睡眠唤醒后的屏幕缩小问题)"`
