### ISSUE TITLE
恢复失败

### ISSUE THREAD

**Issue by harrystudypython** [xzhih/one-key-hidpi#120]
恢复  方法一中 第二次disable找不到那个命令了就

**Comment by xzhih** [comment]
第一次就清理掉了，哪来第二次？

**Comment by harrystudypython** [comment]
好吧 我的现象是disable后屏幕（mbp的屏幕）分辨率还是老样子（和enable的现象一样） 后来我重装系统解决了 还是谢谢了

**Comment by xzhih** [comment]
你给mbp开这个？不是自己就开启了嘛。
原生hidpi别用这个。

**Comment by harrystudypython** [comment]
好的 下次注意 手抖敲错了 谢谢大佬的工具 辛苦啦
