### ISSUE TITLE
脚本执行报错

### ISSUE THREAD

**Issue by huhan-123** [xzhih/one-key-hidpi#124]
![Uploading iShot2020-05-19下午04.31.20.png…]()

**Comment by huhan-123** [comment]
<img width="462" alt="iShot2020-05-19下午04 31 20" src="https://user-images.githubusercontent.com/42287330/82304069-6a207680-99ee-11ea-983d-ad1bc4be7610.png">

**Comment by xzhih** [comment]
在用户目录执行脚本

**Comment by huhan-123** [comment]
好的，谢谢了
