### ISSUE TITLE
Doesn't work for v10.15.4

### ISSUE THREAD

**Issue by GanZ2016** [xzhih/one-key-hidpi#125]
I used Remote Mode and chose (1)Enable HIDPI -> (3)Macbook Pro -> (1)1080p, then reboot.

After reboot, when I went to System Preference -> Displays, I got the "Could not load Displays preference pane" error.

In About This Mac -> Displays, it didn't show the icon.

Please help!

![Screen Shot 2020-05-20 at 21 43 50](https://user-images.githubusercontent.com/25555914/82517687-468b2800-9ae3-11ea-816d-778c6592f21d.png)

![Screen Shot 2020-05-20 at 21 43 41](https://user-images.githubusercontent.com/25555914/82517691-48ed8200-9ae3-11ea-96d6-872b69f7c944.png)

**Comment by xzhih** [comment]
use chose (3) disbale.
wait I will fix

**Comment by qy19920913** [comment]
same problem. wait fix . thanks
