### ISSUE TITLE
Decrease FPS on Catalina -MBP 16

### ISSUE THREAD

**Issue by jk-codes** [xzhih/one-key-hidpi#129]
Monitor 1920x1080 @60hz, Intel HD 530 
Decrease FPS when Using 1680x945.
Playing 4K video losses FPS significantly Choppy.
on 1920x1080 ( 26+ fps)
on 1680x945(15/16+ FPS)

**Comment by xzhih** [comment]
False resolution technology renders at twice the resolution, so GPU performance is critical

**Comment by xzhih** [comment]
GPU performance is not enough
