### ISSUE TITLE
U2515h开启hidpi的问题

### ISSUE THREAD

**Issue by hwanginpen** [xzhih/one-key-hidpi#13]
Hi，

目前我使用的是U2515h 使用type-c to dp的线可以开启1920*1080 hidpi，想问下如果我的macbook pro连接一个type-c的拓展坞，拓展坞支持hdmi 4K/30fps & 1800p/60fps输出的话，若使用hdmi的线连接显示器，是否也一样可以支持开启1920*1080 hidpi的呢？ 其实简单来说就是想问下开启1920*1080 hidpi 是否一定只能用dp的线，hdmi的线可不可以呢？

Cheers,
Jimmy

**Comment by xzhih** [comment]
都可以，只要能识别到显示器，不管是什么连接方式

**Comment by hwanginpen** [comment]
> 都可以，只要能识别到显示器，不管是什么连接方式

好的谢谢你。还想请问下为什么我在Terminal 输入以下命令会无效呀？
$ sh -c "$(curl -fsSL https://raw.githubusercontent.com/xzhih/one-key-hidpi/master/hidpi.sh)"

给我的反馈是：-bash: $: command not found
我应该怎么解决呢？

**Comment by xzhih** [comment]
別把$也复制了啊

**Comment by xzhih** [comment]
另外要记得先关闭 SIP

**Comment by hwanginpen** [comment]
好的谢谢你
