### ISSUE TITLE
mbp 13 为外接2k显示器开启失败 脚本恢复后 缩放顺序混乱

### ISSUE THREAD

**Issue by GodDai** [xzhih/one-key-hidpi#131]
恢复后 缩放顺序混乱 附视频  
[IMG_3400.MOV.zip](https://github.com/xzhih/one-key-hidpi/files/4759123/IMG_3400.MOV.zip)
系统版本10.15.4

**Comment by Yang1k** [comment]
您好  我这里也出现了你的情况，您的问题解决了吗？

**Comment by GodDai** [comment]
> 您好  我这里也出现了你的情况，您的问题解决了吗？
> 
> 

没有解决 系统现在奇奇怪怪的 无奈

**Comment by Yang1k** [comment]
我找到办法了，是一个系统文件被弄乱了，再找一份文件，覆盖进去就行。路径是这里。/System/Library/Displays/Contents/Resources/Overrides/DisplayVendorID-610。我重新找了一份这个目录下的文件，然后拷贝进去就好了，你可以试一试。






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "xzhih/one-key-hidpi"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月26日(星期六) 下午2:19
收件人:&nbsp;"xzhih/one-key-hidpi"<one-key-hidpi@noreply.github.com&gt;;
抄送:&nbsp;"863209913"<863209913@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [xzhih/one-key-hidpi] mbp 13 为外接2k显示器开启失败 脚本恢复后 缩放顺序混乱 (#131)





  
您好  我这里也出现了你的情况，您的问题解决了吗？
  
没有解决 系统现在奇奇怪怪的 无奈

**Comment by xzhih** [comment]
现在更新了新的注入方式和恢复方式
