### ISSUE TITLE
macos big sur 失败

### ISSUE THREAD

**Issue by wtry** [xzhih/one-key-hidpi#133]
<img width="706" alt="image" src="https://user-images.githubusercontent.com/13792519/85402241-ec6ffd80-b58d-11ea-9d47-4478d44835f4.png">

**Comment by xzhih** [comment]
big sur使用了更加严格的系统目录权限，甚至可能SIP都有了调整，我不确定以后还能不能继续更新支持了

**Comment by wtry** [comment]
@xzhih 能在 恢复模式下 手动替换文件吗？

**Comment by Flymeagin** [comment]
MacOS Big Sur失败

**Comment by wtry** [comment]
@Flymeagin @xzhih https://egpu.io/forums/mac-setup/macos-up-to-11/
<img width="846" alt="image" src="https://user-images.githubusercontent.com/13792519/85913995-1bc38a80-b86c-11ea-9840-7846d1ab5f1b.png">

**Comment by xzhih** [comment]
@wtry Great, I will try it recently.

**Comment by stevezhengshiqi** [comment]
@xzhih 其实不需要开启系统目录写入权限。把显示器文件放入 `/Library/Displays/Contents/Resources/Overrides` 是同等效果。这样做的好处是不用 unmount -uw 破坏系统权限，还可以支持 Big Sur 和后续升级。卸载也会方便很多，直接删掉整个 Display 目录即可，可以保护 `/System/Library/Displays/Contents/Resources/Overrides` 目录的纯净。

**Comment by xzhih** [comment]
@stevezhengshiqi 

可以，我很久不搞黑果了，最近又要捡起来搞，老了，心累😂

**Comment by ntol** [comment]
> @xzhih 其实不需要开启系统目录写入权限。把显示器文件放入 `/Library/Displays/Contents/Resources/Overrides` 是同等效果。这样做的好处是不用 unmount -uw 破坏系统权限，还可以支持 Big Sur 和后续升级。
> 
> 卸载也会方便很多，直接删掉整个/Library/Displays/ 目录即可，可以保护 `/System/Library/Displays/Contents/Resources/Overrides` 目录的纯净。
> 
> 我的显卡：UHD620, 1080p, 开启了1440HiDPI分辨率
> 
> <img alt="" width="600" src="https://user-images.githubusercontent.com/36894554/85934541-b1cdd400-b8b1-11ea-9ab1-b794451dbf1c.jpg">

请问，将显示器文件放入 /Library/Displays/Contents/Resources/Overrides之后，再怎么操作呢？谢谢

**Comment by RedTeamWing** [comment]
> /Library/Displays/Contents/Resources/Overrides

求细节

**Comment by RedTeamWing** [comment]
小米34寸的还是很模糊,感觉就是没成功
![image](https://user-images.githubusercontent.com/25416365/87241587-5413bd00-c457-11ea-8caa-f2106177aec5.png)

**Comment by RedTeamWing** [comment]
可以了,我giao,要把憨憨mac盖子盖上,不然获取的id是mac的.

**Comment by xzhih** [comment]
已更新
