### ISSUE TITLE
Not working on Big Sur 10.16 

### ISSUE THREAD

**Issue by jk-codes** [xzhih/one-key-hidpi#138]
Not working on MBP. on BIG SUR 10.16

**Comment by stevezhengshiqi** [comment]
Move the display folder generated by the script to `/Library/Displays/Contents/Resources/Overrides` would also make HiDPI work. And it's a safer place since the system directory is not touched. Hope @xzhih can make changes to it.

**Comment by Flymeagin** [comment]
按照你的方式做了 还是不行  能加个QQ聊吗？QQ1170917384

**Comment by jk-codes** [comment]
Working.. Thanks i changed location in script to L/D..

**Comment by overeggland** [comment]
It seems that in latest official release of Big Sur today, the folder in Library has no longer existed. Is there any alternative?

**Comment by stevezhengshiqi** [comment]
@overeggland The Display folder natively never exists under the Library folder. We need to create that folder, which the script works perfectly.

**Comment by overeggland** [comment]
It works like a treat to me, great help and thanks.

**Comment by overeggland** [comment]
> It works like a treat to me, great help and thanks.



> @overeggland The Display folder natively never exists under the Library folder. We need to create that folder, which the script works perfectly.

It works like a treat to me, great help and thanks.

**Comment by seackone** [comment]
The Script doesnt work for me. After Im choosing my display, the backup failed:

`mkdir: /System/Library/Displays/Contents/Resources/Overrides/HIDPI/backup: Read-only file system
cp: directory /System/Library/Displays/Contents/Resources/Overrides/HIDPI/backup does not exist
cp: /System/Library/Displays/Contents/Resources/Overrides/HIDPI/backup: No such file or directory
cp: /System/Library/Displays/Contents/Resources/Overrides/DisplayVendorID-1e6d: unable to copy extended attributes to /System/Library/Displays/Contents/Resources/Overrides/HIDPI/backup: No such file or directory
cp: /System/Library/Displays/Contents/Resources/Overrides/HIDPI/backup/DisplayProductID-5b11.icns: No such file or directory
cp: /System/Library/Displays/Contents/Resources/Overrides/HIDPI/backup/DisplayProductID-5b10.icns: No such file or directory
cp: /System/Library/Displays/Contents/Resources/Overrides/HIDPI/backup/DisplayProductID-76d8: No such file or directory
cp: /System/Library/Displays/Contents/Resources/Overrides/HIDPI/backup/DisplayProductID-5b74.tiff: No such file or directory
cp: /System/Library/Displays/Contents/Resources/Overrides/HIDPI/backup/DisplayProductID-5b11.mtdd: No such file or directory
cp: /System/Library/Displays/Contents/Resources/Overrides/HIDPI/backup/DisplayProductID-5b7b.tiff: No such file or directory
cp: /System/Library/Displays/Contents/Resources/Overrides/HIDPI/backup/DisplayProductID-5b74.icns: No such file or directory
cp: /System/Library/Displays/Contents/Resources/Overrides/HIDPI/backup/DisplayProductID-7721.mtdd: No such file or directory
cp: /System/Library/Displays/Contents/Resources/Overrides/HIDPI/backup/DisplayProductID-76e7: No such file or directory
cp: /System/Library/Displays/Contents/Resources/Overrides/HIDPI/backup/DisplayProductID-76e6: No such file or directory
cp: /System/Library/Displays/Contents/Resources/Overrides/HIDPI/backup/DisplayProductID-5b7b.icns: No such file or directory
cp: /System/Library/Displays/Contents/Resources/Overrides/HIDPI/backup/DisplayProductID-76db: No such file or directory
cp: /System/Library/Displays/Contents/Resources/Overrides/HIDPI/backup/DisplayProductID-5b11.tiff: No such file or directory
cp: /System/Library/Displays/Contents/Resources/Overrides/HIDPI/backup/DisplayProductID-5b10.tiff: No such file or directory
cp: /System/Library/Displays/Contents/Resources/Overrides/HIDPI/backup/DisplayProductID-5b74: No such file or directory
cp: /System/Library/Displays/Contents/Resources/Overrides/HIDPI/backup/DisplayProductID-5b11: No such file or directory
cp: /System/Library/Displays/Contents/Resources/Overrides/HIDPI/backup/DisplayProductID-5b74.mtdd: No such file or directory
cp: /System/Library/Displays/Contents/Resources/Overrides/HIDPI/backup/DisplayProductID-5b7b: No such file or directory
cp: /System/Library/Displays/Contents/Resources/Overrides/HIDPI/backup/DisplayProductID-5b10: No such file or directory
mv: rename /Users/Christoph/Downloads/one-key-hidpi-master/tmp/disable to /System/Library/Displays/Contents/Resources/Overrides/HIDPI/: No such file or directory
chmod: /System/Library/Displays/Contents/Resources/Overrides/HIDPI/disable: No such file or directory`

If im trying to change the resolution at my external display to a custom resolution, the script seems to work:

`cp: /System/Library/Displays/Contents/Resources/Overrides/DisplayVendorID-1e6d/DisplayProductID-76db.icns: Read-only file system
cp: /System/Library/Displays/Contents/Resources/Overrides/DisplayVendorID-1e6d/DisplayProductID-76db: Read-only file system
cp: /System/Library/Displays/Contents/Resources/Overrides/Icons.plist: Read-only file system
Enabled, please reboot.
Rebooting the logo for the first time will become huge, then it will not be.
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.
`

But after reboot, nothing happend. Im not able to select the new resolution.

**Comment by stevezhengshiqi** [comment]
@seackone Please use dev fork. Run `bash -c "$(curl -fsSL https://raw.githubusercontent.com/xzhih/one-key-hidpi/dev/hidpi.sh)"`

**Comment by seackone** [comment]
thank your for your fast response. works perfectly now!

**Comment by armadeas** [comment]
Thanks it's work 

> @seackone Please use dev fork on Big Sur. Run `bash -c "$(curl -fsSL https://raw.githubusercontent.com/xzhih/one-key-hidpi/dev/hidpi.sh)"`
