### ISSUE TITLE
白苹果把内建显示器搞坏了

### ISSUE THREAD

**Issue by luhuiyang** [xzhih/one-key-hidpi#14]
使用mbp 2018，想开启外接显示器，结果把内建显示器搞坏了，内建显示器vendid是610，disable以后，并没有恢复610的配置文件，系统设置界面的显示器样式也从mbp变成显示器，没办法只能重装，看了其他issues，好像是要盒盖用该脚本？希望增加选项，或者提示

**Comment by xzhih** [comment]
已添加外置屏幕选择
