### ISSUE TITLE
Stuck at "password:?" when running this application

### ISSUE THREAD

**Issue by ars4l4n** [xzhih/one-key-hidpi#141]
I ran the application by opening the file "hidpi.command", terminal opens and then it says "password:?"
I can't type anything into the terminal then. 
Edit: I copy pasted my password using rightclick->paste and then pressing enter and it worked (although there is still no feedback on the screen that my password was entered)
Also, I needed to try this multiple times. It didn't work the first time. Don't know why it behaves like this

**Comment by xzhih** [comment]
In Unix, the password entered on the command line is hidden for security, but in fact it is valid when you enter it
