### ISSUE TITLE
10.15.16系统关闭失败

### ISSUE THREAD

**Issue by XS170202102451** [xzhih/one-key-hidpi#147]
使用./disable关闭和手动关闭都不行，系统缩放分辨率顺序错误，内置显示器不能原以原分辨率显示，外接显示器黑屏，求解

**Comment by CalvertDXie** [comment]
同10.15.16，显示默认设置看起来缩放比原来大

**Comment by CalvertDXie** [comment]
你可以拿用time machine把vendor ID下之前的文件复制出来，然后覆盖进去。我已经恢复了

**Comment by Yang1k** [comment]
> 你可以拿用time machine把vendor ID下之前的文件复制出来，然后覆盖进去。我已经恢复了

要恢复哪里的文件？

**Comment by Yang1k** [comment]
> 你可以拿用time machine把vendor ID下之前的文件复制出来，然后覆盖进去。我已经恢复了

n弄好了  谢谢啦

**Comment by Csj1996** [comment]
如何覆盖啊

**Comment by xzhih** [comment]
更新了新的注入方式和恢复方式
