### ISSUE TITLE
关于Intel HD4000显卡在2k显示器上4k渲染的疑问

### ISSUE THREAD

**Issue by YIN-Renlong** [xzhih/one-key-hidpi#148]
设备为Macbook Pro Mid 2012, CPU为 i5-3210M，显卡为 HD Graphics 4000，输出为miniDP。

用此脚本后，系统显示为：

![image](https://user-images.githubusercontent.com/9191251/93750607-05736380-fbfc-11ea-8fd9-e83404acb28f.png)

显示器（华硕 PA279Q）上的信息显示为2560x1440 8KHz/60Hz

但苹果的官方信息告知，这台电脑最高输出为 2560x1600 （https://support.apple.com/kb/sp649?locale=en_US）：

![image](https://user-images.githubusercontent.com/9191251/93750881-80d51500-fbfc-11ea-8406-d9a9e89a8904.png)

一个帖子中表示 HD Graphics 4000 最高输出为 3840x2160 30Hz （https://superuser.com/questions/964703/what-is-the-maximum-display-resolution-on-the-intel-hd-graphics-4000-chipset-on#:~:text=Intel%20HD%20Graphics%204000%20supports,2560%C3%971600%20through%20DisplayPort.）。

疑问是：使用了HiDPI之后，显卡的实际输出分辨率和频率是多少？多谢。

**Comment by xzhih** [comment]
以显示器的为准

**Comment by YIN-Renlong** [comment]
> 以显示器的为准

感谢回复。但若HD 4000支持3840x2160 30Hz，移动鼠标的时候理论上会感到卡顿。但实际情况体验正常。是否可以认为此显卡以1920x1080的缩放输出2560x1440？

**Comment by YIN-Renlong** [comment]
> 以显示器的为准

另外一个问题望确认下：HiDPI 是否会和显示器的ICC配置文件产生冲突？因为显示器已经用Spyder Pro较色，并配置了单独的ICC文件。开启HiDPI之后是否需要重新较色？感谢！

**Comment by xzhih** [comment]
1. UI 上以 3840x2160 分辨率按照宽高 2 合 1 缩放为 1920x1080 的比例（对应系统报告中的“UI看起来类似”），事实上也是以 3840x2160  渲染的（对应系统报告中的“分辨率”）。但是系统读取到显示器 EDID 中实际分辨率为 2560x1440，所以以 2560x1440 的数据流传输给显示器的驱动板。

所以应该是以 3840x2160 缩放输出 2560x1440 才对。

2. 开启HiDPI之后一般不需要重新校色，因为只是在 EDID 中开启了强制显示器输入 RGB 色彩，不会影响到实际表现，也不会和 ICC 配置文件产生冲突。

**Comment by YIN-Renlong** [comment]
> 1. UI 上以 3840x2160 分辨率按照宽高 2 合 1 缩放为 1920x1080 的比例（对应系统报告中的“UI看起来类似”），事实上也是以 3840x2160  渲染的（对应系统报告中的“分辨率”）。但是系统读取到显示器 EDID 中实际分辨率为 2560x1440，所以以 2560x1440 的数据流传输给显示器的驱动板。
> 
> 所以应该是以 3840x2160 缩放输出 2560x1440 才对。
> 
> 1. 开启HiDPI之后一般不需要重新校色，因为只是在 EDID 中开启了强制显示器输入 RGB 色彩，不会影响到实际表现，也不会和 ICC 配置文件产生冲突。

多谢详细的解答！

同时，这是否意味着HD 4000能够分辨率3840 x 2160在60Hz的频率（59.88 Hz/NTSC）工作？这个事实是否与英特尔的官方参数(3840x2160 最高 30Hz)相违背？

![image](https://user-images.githubusercontent.com/9191251/93785001-e2fa3e00-fc2d-11ea-9db7-c8f7999f8ff1.png)

**Comment by xzhih** [comment]
我认为没有违背英特尔的官方参数和DisplayPort 1.1的接口参数。

渲染分辨率和输出分辨率是不同的，在游戏里也很常见啊，就是把画面以几倍渲染再缩放输出，得到更精细的画面。

而实际输出为 2560x1440，也还在DisplayPort 1.1的支持范围内。

**Comment by YIN-Renlong** [comment]
> 我认为没有违背英特尔的官方参数和DisplayPort 1.1的接口参数。
> 
> 渲染分辨率和输出分辨率是不同的，在游戏里也很常见啊，就是把画面以几倍渲染再缩放输出，得到更精细的画面。
> 
> 而实际输出为 2560x1440，也还在DisplayPort 1.1的支持范围内。

是否可以认为显卡以3840x2160 30Hz渲染，然后以2560x1440 60Hz输出？

**Comment by xzhih** [comment]
渲染的帧数不太清楚，一般是变动的，然后先储存在Framebuffer里吧。

**Comment by YIN-Renlong** [comment]
> 渲染的帧数不太清楚，一般是变动的，然后先储存在Framebuffer里吧。

感谢回复，不知是否有方法能够查看渲染帧数的实时数据？

**Comment by xzhih** [comment]
<img width="272" alt="截屏2020-09-24 11 30 38" src="https://user-images.githubusercontent.com/13920737/94097603-6055c680-fe59-11ea-9c9c-92a157a37433.png">

用 iStat Menus

**Comment by wangnan789** [comment]
> > 1. UI 上以 3840x2160 分辨率按照宽高 2 合 1 缩放为 1920x1080 的比例（对应系统报告中的“UI看起来类似”），事实上也是以 3840x2160  渲染的（对应系统报告中的“分辨率”）。但是系统读取到显示器 EDID 中实际分辨率为 2560x1440，所以以 2560x1440 的数据流传输给显示器的驱动板。
> > 
> > 所以应该是以 3840x2160 缩放输出 2560x1440 才对。
> > 
> > 1. 开启HiDPI之后一般不需要重新校色，因为只是在 EDID 中开启了强制显示器输入 RGB 色彩，不会影响到实际表现，也不会和 ICC 配置文件产生冲突。
> 
> 多谢详细的解答！
> 
> 同时，这是否意味着HD 4000能够分辨率3840 x 2160在60Hz的频率（59.88 Hz/NTSC）工作？这个事实是否与英特尔的官方参数(3840x2160 最高 30Hz)相违背？
> 
> Macbook Pro Mid 2012 使用的是雷电1下的DisplayPort 1.1版本（8.64 Gbps，[链接](https://www.apple.com/shop/question/answers/product/MMEL2AM/A/will-this-adapter-allow-me-to-connect-a-macbook-air-or-a-15-macbook-pro-mid2012-to-an-lg-ultrafine-22md4kab-display/QKTT9KYA2TXXDTTH2)），DisplayPort 1.1的最高支持3840 x 2160 @ 30 Hz。这是否也与输出60Hz的事实相违背？
> 
> 希望能够解答这个疑惑。感谢。
> 
> 缩放界面按住Option键后的截图：
> 
> ![image](https://user-images.githubusercontent.com/9191251/93785001-e2fa3e00-fc2d-11ea-9db7-c8f7999f8ff1.png)

违背了吗？？？你能运行在4k60Hz吗？？？
