### ISSUE TITLE
机械革命S1休眠后分辨率错乱

### ISSUE THREAD

**Issue by sonadd** [xzhih/one-key-hidpi#15]
休眠后画面只在屏幕左上方显示完整桌面，其余地方黑屏

**Comment by xzhih** [comment]
选项 2 是打花屏补丁的，你可以试试

**Comment by sonadd** [comment]
谢谢，已经试过了，依然如此

**Comment by xzhih** [comment]
什么版本的系统？确保显卡驱动正确了，先关闭 hidpi 有没有这样的情况。

**Comment by sonadd** [comment]
10.13.6-10.14均有这个问题，显卡驱动正常，目前发现再休眠一次就会恢复正常显示，但是只要改过缩放，就会有闪屏的情况，默认的1080P就不会

**Comment by xzhih** [comment]
在10.13.3之前我有遇到过，但是之后就没有遇到了，我 dell 燃 7000 这个机型有 LG 和奇美两种面板，LG的就没啥问题，奇美开 hidpi 就有闪屏，不过 10.13.6 没有再发现了

**Comment by xzhih** [comment]
已更新修复
