### ISSUE TITLE
mac 11.0.1 hidpi open fail

### ISSUE THREAD

**Issue by I-m-SuperMan** [xzhih/one-key-hidpi#154]
Mac 11.0.1 hidpi open fail.

**Comment by I-m-SuperMan** [comment]
cp: /System/Library/Displays/Contents/Resources/Overrides/DisplayVendorID-220e: Read-only file system
cp: ./tmp/DisplayVendorID-220e: unable to copy extended attributes to /System/Library/Displays/Contents/Resources/Overrides/DisplayVendorID-220e: Read-only file system
cp: /System/Library/Displays/Contents/Resources/Overrides/DisplayVendorID-220e/DisplayProductID-3475: No such file or directory

**Comment by xzhih** [comment]
你用的是最新的脚本吗，然后选择了哪些个选项

**Comment by I-m-SuperMan** [comment]
> 你用的是最新的脚本吗，
Used this script : https://raw.githubusercontent.com/xzhih/one-key-hidpi/master/hidpi.sh

> 然后选择了哪些个选项
显示器：2    |    220e    |         |  HP E273q
开启HIDPI(同时注入EDID) 2
选择显示器ICON： (6) 保持原样
选择分辨率配置： 2560x1440 显示屏

**Comment by xzhih** [comment]
新版得脚本不会写入System了，你可以重试一下

**Comment by stevezhengshiqi** [comment]
@I-m-SuperMan You should use dev fork. Run `bash -c "$(curl -fsSL https://raw.githubusercontent.com/xzhih/one-key-hidpi/dev/hidpi.sh)"` or use the off-line script in https://github.com/xzhih/one-key-hidpi/tree/dev

**Comment by xzhih** [comment]
@stevezhengshiqi 脚本更新过了，实在不知道他是啥问题

**Comment by I-m-SuperMan** [comment]
Thanks for replaying.  New script works fine!
