### ISSUE TITLE
arm架构的mac mini似乎无法打开

### ISSUE THREAD

**Issue by wlmdmy** [xzhih/one-key-hidpi#156]
用了最新的脚本，自己尝试直接把屏幕配置文件放入/Library/Displays/Contents/Resources/，均无效

**Comment by caili632** [comment]
是的，我刚买的mac mini连接2k显示器，试了各种办法都没成功，希望大神能研究下m1芯片如何开启hidpi

**Comment by xzhih** [comment]
Duplicate of #157
