### ISSUE TITLE
mojave上开启后，闪屏

### ISSUE THREAD

**Issue by konstant2016** [xzhih/one-key-hidpi#16]
我的笔记本是小米pro:
处理器：i7-8550U
显卡：HD620/MX150
目前驱动的是HD620显卡
用您的脚本，在10.13.6上可以正常开启HIDPI并使用，但是升级到10.14（格盘重装、覆盖升级都试过）后，重启正常，睡眠再唤醒后，屏幕就开始出现雪花状的块斑，位置不定，只要有界面刷新，就会出现，大佬可否抽空研究一下？

**Comment by xzhih** [comment]
10.14 的我还没升级，你可以试试选项 2，它是打花屏补丁的，不过可能会出现模糊过渡不自然的情况

**Comment by sonadd** [comment]
跟我的情况差不多，我是机械革命S1，处理器：i5-8250U，显卡：UHD620

**Comment by konstant2016** [comment]
感谢回复，选项2试过了，情况依旧，期待大佬解决

**Comment by diemus** [comment]
我也有这个情况，这么说来是10.14系统的问题

**Comment by fnoopv** [comment]
首先尝试提升cursormemory大小，其次可以尝试提升显存大小和注入EDID。一模一样的问题，我的hd4600是通过提升cursormemory大小解决的，一个热补丁

**Comment by xzhih** [comment]
@fnoopv cursormem是Haswell特有的

**Comment by fnoopv** [comment]
> @fnoopv cursormem是Haswell特有的

那就不太清楚了，或许可以试试其他两个

**Comment by xzhih** [comment]
选择手动输入分辨率 1680x945 1424x802 1280x720 1024x576，回车，然后重启

在设置里选择1424x802这个分辨率看看

**Comment by xuzhaoqing** [comment]
> 选择手动输入分辨率 1680x945 1424x802 1280x720 1024x576，回车，然后重启
> 
> 在设置里选择1424x802这个分辨率看看

这个方法实测有效

**Comment by konstant2016** [comment]
选择选择1424x802分辨率时，正常！感谢楼上各位大神的回复，问题已解决
