### ISSUE TITLE
3440x1440的带鱼屏支持吗   系统是Big Sur 11.2.1

### ISSUE THREAD

**Issue by WangPe1n** [xzhih/one-key-hidpi#170]
![image](https://user-images.githubusercontent.com/22020970/108824901-433a4500-75fd-11eb-9fc1-241c0bda3a1a.png)
![image](https://user-images.githubusercontent.com/22020970/108824972-5ea55000-75fd-11eb-9e17-c045670a6c67.png)

**Comment by WangPe1n** [comment]
亲测支持，但是要先关闭SIP。
[https://www.zhihu.com/question/299116142/answer/1181187751](参考链接)

**Comment by ssikiki** [comment]
big sur系统 + 飞利浦带鱼屏， 关了sip， 按文档设置了2560x1072 5120x2144， 重启进系统缩放那里还是只能配置分辨率， 是哪里姿势不对么？

**Comment by JayShen1943** [comment]
> MBP2018 big sur系统 + 飞利浦带鱼屏， 关了sip， 按文档设置了2560x1072 5120x2144， 重启进系统缩放那里还是只能配置分辨率， 是哪里姿势不对么？

一样，你解决了吗
