### ISSUE TITLE
提供一个Repo - 从开启RGB想到的

### ISSUE THREAD

**Issue by arthurire** [xzhih/one-key-hidpi#174]
目前在Dell U2720QM 上开启了RGB,方法是从Intel机器上生成Patch复制到M1机器上...

[https://gist.github.com/adaugherity/7435890](url)

One-key-hidpi这样做可行吗?

**Comment by xzhih** [comment]
不可行

不是个通用的方法，每台显示器 EDID 不一样，而且插在不同的接口 EDID 也不同

**Comment by arthurire** [comment]
> 不可行
> 
> 不是个通用的方法，每台显示器 EDID 不一样，而且插在不同的接口 EDID 也不同

明白了 谢谢!
