### ISSUE TITLE
进入画面logo变大

### ISSUE THREAD

**Issue by berwincc** [xzhih/one-key-hidpi#18]
你好，
我发现进入画面，logo每一次都会变大，而且闪屏。我用了恢复的方式，但是依然没有效果。请问还有别的方式恢复吗？

**Comment by xzhih** [comment]
1. 没看说明的吗，logo 变大我有说明
2. 关闭 hidpi 就不会变大了，重新运行脚本，选择关闭
3. 关闭 hidpi 后还闪屏，那就是其他的问题，脚本只创建新的配置文件，没有对其他东西修改，闪屏只能是其他原因

**Comment by berwincc** [comment]
> 1. 没看说明的吗，logo 变大我有说明
> 2. 关闭 hidpi 就不会变大了，重新运行脚本，选择关闭
> 3. 关闭 hidpi 后还闪屏，那就是其他的问题，脚本只创建新的配置文件，没有对其他东西修改，闪屏只能是其他原因

谢谢。
我看到说明，但是不知道如何解决。 我已经排除，问题和脚本无关。谢谢
