### ISSUE TITLE
Extra resolution screen with no resolution attached to it?

### ISSUE THREAD

**Issue by jordanshaikly** [xzhih/one-key-hidpi#181]
Hi,

My scale settings has 5 resolution options for HiDPi but yet only the 4 to the right work and the one to the left does nothing.

Anyway to remove the one that doesn't work or assign a resolution to it?

![ezgif-2-7799f76b1337](https://user-images.githubusercontent.com/18117157/114190809-a1b84a00-9943-11eb-80a6-ea5f1bc04792.gif)

**Comment by xzhih** [comment]
Use `Manual input resolution` option, input what you want to show in the setting.

**Comment by jordanshaikly** [comment]
Issue fixed in new display settings area in macOS Monterey.
