### ISSUE TITLE
m1开启hidpi的一点新思路?

### ISSUE THREAD

**Issue by 0626-NG** [xzhih/one-key-hidpi#187]
最近购入m1 mac mini，查阅并尝试各种hidpi开启方法都无果，貌似m1 Macbook air配合SwitchResX再插拔扩展坞的成功案例比较多，也有失败案例貌似是扩展坞问题不行的，我的mini是明确不行的。
把玩m1同时，好奇心驱使我下载以前windows上用过的Duet Display，一个可以拿旧平板当作副屏的软件。当时在win上体验不好，现在在m1 Mac上反而有惊喜，我的ipad mini 2 （老平板不能随航）接上后明确能开启hidpi，整体体验还可以，目测也是明确开启了，而且SwitchResX也正确识别出hidpi的分辨率，反而两个ID没完全识别。有兴趣的朋友可以研究下。

![截屏2021-05-18 下午11 35 56](https://user-images.githubusercontent.com/43025388/118683802-4035a600-b834-11eb-9d7c-f1fce124655d.png)

没折腾成功的主屏幕信息
![截屏2021-05-18 下午11 36 37](https://user-images.githubusercontent.com/43025388/118683822-43c92d00-b834-11eb-871a-e1e092ba45cd.png)
![截屏2021-05-18 下午11 36 45](https://user-images.githubusercontent.com/43025388/118683826-4461c380-b834-11eb-8c6f-1e1f6d6a1701.png)

**Comment by cosine7** [comment]
我也是 m1 mac mini，参考了 #157 ，买了个EDID emulator，接在HDMI上，然后用C to DP 连接显示器，如下图

![IMG_4940](https://user-images.githubusercontent.com/48633709/118860189-18ccf080-b8a9-11eb-8829-5aa2548eed00.jpg)

接着在switchResX里面给EDID emulator设置了一下Startup resolution和Scaled resolution base，保存并重启，如下图

<img width="1082" alt="截屏2021-05-19 下午2 05 12" src="https://user-images.githubusercontent.com/48633709/118862220-7104f200-b8ab-11eb-9d45-9c0b2e342930.png">

最后到控制中心里面设置一下镜像就可以了。

<img width="1336" alt="截屏2021-05-19 下午2 15 58" src="https://user-images.githubusercontent.com/48633709/118863357-cb528280-b8ac-11eb-8c66-421e0146887c.png">

我尝试过直连EDID emulator，但是我显示器提示输入不支持，然而用ipad随航查看发现HiDPI已经开启了，没办法只能镜像了，可能是我显示器的问题吧。。。

**Comment by 0626-NG** [comment]
> 我也是 m1 mac mini，参考了 #157 ，买了个EDID emulator，接在HDMI上，然后用C to DP 连接显示器，如下图
> 
> ![IMG_4940](https://user-images.githubusercontent.com/48633709/118860189-18ccf080-b8a9-11eb-8829-5aa2548eed00.jpg)
> 
> 接着在switchResX里面给EDID emulator设置了一下Startup resolution和Scaled resolution base，保存并重启，如下图
> （我这个EDID emulator 刚接上的时候默认1920 * 1080，所以或许可以不用switchResX设置这些东西，可能到偏好设置里改成4k分辨率也行）
> <img alt="截屏2021-05-19 下午2 05 12" width="1082" src="https://user-images.githubusercontent.com/48633709/118862220-7104f200-b8ab-11eb-9d45-9c0b2e342930.png">
> 
> 最后到控制中心里面设置一下镜像就可以了。
> 
> <img alt="截屏2021-05-19 下午2 15 58" width="1336" src="https://user-images.githubusercontent.com/48633709/118863357-cb528280-b8ac-11eb-8c66-421e0146887c.png">
> 
> 我尝试过直连EDID emulator，但是我显示器提示输入不支持，然而用ipad随航查看发现HiDPI已经开启了，没办法只能镜像了，可能是我显示器的问题吧。。。

感谢分享成功案例。

**Comment by zungjam** [comment]
> > 我也是 m1 mac mini，参考了 #157 ，买了个EDID emulator，接在HDMI上，然后用C to DP 连接显示器，如下图
> > ![IMG_4940](https://user-images.githubusercontent.com/48633709/118860189-18ccf080-b8a9-11eb-8829-5aa2548eed00.jpg)
> > 接着在switchResX里面给EDID emulator设置了一下Startup resolution和Scaled resolution base，保存并重启，如下图
> > （我这个EDID emulator 刚接上的时候默认1920 * 1080，所以或许可以不用switchResX设置这些东西，可能到偏好设置里改成4k分辨率也行）
> > <img alt="截屏2021-05-19 下午2 05 12" width="1082" src="https://user-images.githubusercontent.com/48633709/118862220-7104f200-b8ab-11eb-9d45-9c0b2e342930.png">
> > 最后到控制中心里面设置一下镜像就可以了。
> > <img alt="截屏2021-05-19 下午2 15 58" width="1336" src="https://user-images.githubusercontent.com/48633709/118863357-cb528280-b8ac-11eb-8c66-421e0146887c.png">
> > 我尝试过直连EDID emulator，但是我显示器提示输入不支持，然而用ipad随航查看发现HiDPI已经开启了，没办法只能镜像了，可能是我显示器的问题吧。。。
> 
> 感谢分享成功案例。

也买了这个emulator，但是一保存选项就全部还原了

**Comment by ScarletWang** [comment]
有任何更新嗎？爬了很多文，結果給2K螢幕還是不行....

**Comment by cosine7** [comment]
> 也买了这个emulator，但是一保存选项就全部还原了

switchResX激活了吗？我的switchResX是4.11.1版本并且激活了的。然后如果你是通过display选项下面的write system settings来保存的话有时候确实会重置，但是commend + s来保存就没问题。

**Comment by k-skye** [comment]
> 我也是 m1 mac mini，参考了 #157 ，买了个EDID emulator，接在HDMI上，然后用C to DP 连接显示器，如下图
> 
> ![IMG_4940](https://user-images.githubusercontent.com/48633709/118860189-18ccf080-b8a9-11eb-8829-5aa2548eed00.jpg)
> 
> 接着在switchResX里面给EDID emulator设置了一下Startup resolution和Scaled resolution base，保存并重启，如下图
> （我这个EDID emulator 刚接上的时候默认1920 * 1080，所以或许可以不用switchResX设置这些东西，可能到偏好设置里改成4k分辨率也行）
> <img alt="截屏2021-05-19 下午2 05 12" width="1082" src="https://user-images.githubusercontent.com/48633709/118862220-7104f200-b8ab-11eb-9d45-9c0b2e342930.png">
> 
> 最后到控制中心里面设置一下镜像就可以了。
> 
> <img alt="截屏2021-05-19 下午2 15 58" width="1336" src="https://user-images.githubusercontent.com/48633709/118863357-cb528280-b8ac-11eb-8c66-421e0146887c.png">
> 
> 我尝试过直连EDID emulator，但是我显示器（2k 144）提示输入不支持，然而用ipad随航查看发现HiDPI已经开启了，没办法只能镜像了，可能是我显示器的问题吧。。。

感谢！！某宝买了同款，直接连上之后打开镜像就可以了，确实可以不用switchResX设置这些东西～！！！！成功了！！
