### ISSUE TITLE
60hz refresh rate not available in 144hz monitor

### ISSUE THREAD

**Issue by jericopulvera** [xzhih/one-key-hidpi#198]
I got a Mi 34 inch monitor with a 144hz refresh rate. Is choosing 60hz or 144hz not possible?

![image](https://user-images.githubusercontent.com/23246308/126848459-e19e4b38-76ca-49f7-9094-63b7d44232bd.png)

**Comment by BH1SCW** [comment]
I got Mi 34inch monitor too， but still 50 hz when HIDPI enabled.

**Comment by johnny12150** [comment]
I think that's totally normal. Even if you use an app such as SwitchResX to enable HiDPI on external monitors, you will still get the same result.

**Comment by BH1SCW** [comment]
> I think that's totally normal. Even if you use an app such as SwitchResX to enable HiDPI on external monitors, you will still get the same result.

https://www.zhihu.com/question/420223903/answer/2037786054

but it does't work for me 🔢
