### ISSUE TITLE
【SIP】没有权限

### ISSUE THREAD

**Issue by nuomi1** [xzhih/one-key-hidpi#2]
白苹果 10.13.4。

没有关闭 SIP 的情况下，`/System/Library/Displays/Contents/Resources/Overrides` 没有写入权限。

文中并没有提及，望更新。

**Comment by weaming** [comment]
白苹果 10.13.5 同样情况。

看到禁用 rootless 的文章 https://www.howtogeek.com/230424/how-to-disable-system-integrity-protection-on-a-mac-and-why-you-shouldnt/ 但是要到 Recovery OS

```
$ csrutil disable
csrutil: failed to modify system integrity configuration. This tool needs to be executed from the Recovery OS.
```

**Comment by cwr31** [comment]
> 白苹果 10.13.5 同样情况。
> 
> 看到禁用 rootless 的文章 https://www.howtogeek.com/230424/how-to-disable-system-integrity-protection-on-a-mac-and-why-you-shouldnt/ 但是要到 Recovery OS
> 
> ```
> $ csrutil disable
> csrutil: failed to modify system integrity configuration. This tool needs to be executed from the Recovery OS.
> ```

禁用了仍然复制不进去

**Comment by xzhih** [comment]
已增加 SIP 状态检测
