### ISSUE TITLE
some error:   sed:  unescaped newline inside substitute 

### ISSUE THREAD

**Issue by BH1SCW** [xzhih/one-key-hidpi#202]
Enter your choice: 6
Enter the HIDPI resolution, separated by a space，like this: 1680x945 1600x900 1440x810
:2560x1072 5120x2144
sed: 1: "s:EDid:AP///////wBhqUQ0 ...": unescaped newline inside substitute pattern
Enabled, please reboot.
Rebooting the logo for the first time will become huge, then it will not be.

看起来像是个bug？

**Comment by xzhih** [comment]
用`dev分支`试试，我调整了下`sed`输出

**Comment by BH1SCW** [comment]
行，我可以帮忙测试一下
我昨晚按网上教程，手动生成了一份xml的配置文件，用RDM倒是可以设置正确的分辨率不过有两个问题需要请教一下
1， 我都控制面板显示中没有缩放的那几个选项，内建显示器是有的，RDM是有闪电标志，这个HIDPI是否正常开启了？
2，刷新频率只有50HZ， 查询得知需要PD1.4的线材和type c转DP接口，这点我也满足了，你这个工具除了会自动生成配置文件还有什么地方能影响上面两个问题的吗？
非常感谢~~

**Comment by xzhih** [comment]
主要就是方便生成多个分辨率档位的配置文件，再一个是注入修正的 EDID 信息，修复一些开启 hidpi 后产生的颜色不正常和闪屏问题，也不一定能修复。

**Comment by BH1SCW** [comment]
试了一下， dev分支的Edid也会报错

**Comment by BH1SCW** [comment]
> EDID 修复闪屏，或者睡眠唤醒后的闪屏问题

我发现开了HIDPI，在锁屏后回来，输入完密码后 Window Server会挂掉， 所有桌面运行程序会重新加载，不知道这个问题是不是上面描述的闪屏？我用默认分辨率不会有这个问题

**Comment by BH1SCW** [comment]
目前一段时间用已经没有挂掉的问题了
