### ISSUE TITLE
Big Sur 11.5.2 系统不生效

### ISSUE THREAD

**Issue by songhao8080** [xzhih/one-key-hidpi#208]
硬件：MacBook Pro (Retina, 15-inch, Mid 2015)
系统：Big Sur 11.5.2
测试了几次，依然不生效

**Comment by AndyEverLie** [comment]
刚刚试了， Big Sur 11.6.1 (20G224)
你需要进入recovery的terminal，将SIP关闭
输入命令
`csrutil disable`
