### ISSUE TITLE
三星C27JG5x 2K分辨率,无法开启HIDPI

### ISSUE THREAD

**Issue by yooranchen** [xzhih/one-key-hidpi#21]
脚本跑完重启后,只是显示器缩放栏目多了大于2k的选项,,并没有开启HIDPI

**Comment by yooranchen** [comment]
系统版本,10.13.6 (17G65)
我用1080P的显示器是可以开启的

**Comment by xzhih** [comment]
用 RDM 看看

**Comment by yooranchen** [comment]
多谢,, RDM的话,和你这边运行完的效果一样,都是只能调整分辨率,
现在如果是2K调整到1080P的话,确实字体会变大,但是变得模糊

ZeRo Xu <notifications@github.com> 于2018年11月10日周六 下午3:53写道：

**Comment by xzhih** [comment]
你是笔记本还是主机？主机用的独显吗？
如果是笔记本或者主机没独显，请用 fb-patch 破解 HDMI20(4k)
独显的话，使用 DP 接口

**Comment by yooranchen** [comment]
台式机，独显，用的是dp接口没错

ZeRo Xu <notifications@github.com> 于 2018年11月11日周日 16:38写道：

**Comment by xzhih** [comment]
那你尝试用手动输入分辨率的选项，如果不行，就放弃使用这个脚本吧，用其它的方式开启

**Comment by xzhih** [comment]
无法开启时，使用手动输入选项，输入更高的分辨率
