### ISSUE TITLE
黑苹果装Monterey脚本失效

### ISSUE THREAD

**Issue by BrushXue** [xzhih/one-key-hidpi#216]
别人都报M1没法用，我这Intel也没法用了。
经测试是`ioreg -lw0`这一步会卡死，同样的硬件配置装Catalina和Big Sur都没有问题。

**Comment by laodiaoyadashu** [comment]
> 别人都报M1没法用，我这Intel也没法用了。 经测试是`ioreg -lw0`这一步会卡死，同样的硬件配置装Catalina和Big Sur都没有问题。

遇到了同样的问题，系统是12.1，请问你现在解决了吗

**Comment by BrushXue** [comment]
无解啊，等解决方案吧。

**Comment by labulaka521** [comment]
可以正常执行 但是好像没什么效果

**Comment by BrushXue** [comment]
> > 别人都报M1没法用，我这Intel也没法用了。 经测试是`ioreg -lw0`这一步会卡死，同样的硬件配置装Catalina和Big Sur都没有问题。
> 
> 遇到了同样的问题，系统是12.1，请问你现在解决了吗

@laodiaoyadashu 无意间发现插了第二台显示器上去，脚本就可以正常运行了。
