### ISSUE TITLE
使用后无法压缩

### ISSUE THREAD

**Issue by 396192074** [xzhih/one-key-hidpi#25]
1、使用后文件夹右键点压缩，响一声后没反应。发现于macOS 10.14.2和10.12.6。
2、使用后预览图片，finder卡住，发现于macOS 10.12.6。
3、使用后Photo Booth拍照卡住，发现于macOS 10.12.6。

**Comment by xzhih** [comment]
icon.plist 来自 10.14，不清楚是否适用于 10.12，因此10.12选择保留原icon最好
脚本没有对其他任何文件做修改，只是添加了一个屏幕配置文件，这个自己看源码就懂
因此你上述的第一个问题我觉得与脚本无关，而二、三问题我认为与显卡驱动有关
