### ISSUE TITLE
有办法把重启的字体调正常吗

### ISSUE THREAD

**Issue by fengfst** [xzhih/one-key-hidpi#27]
有办法把重启的字体调正常，重启的时候界面（-v现实的字体）的字体过小，有办法解决吗

**Comment by xzhih** [comment]
没办法

**Comment by xzhih** [comment]
正常使用没人开 `-v` 模式的，要调试的话，还是关了 `hidpi` 吧

**Comment by fengfst** [comment]
感谢




| |
fengfst
|
|
fengfst@126.com
|
签名由网易邮箱大师定制
在2019年1月3日 20:39，ZeRo Xu<notifications@github.com> 写道：

正常使用没人开 -v 模式的，要调试的话，还是关了 hidpi 吧
