### ISSUE TITLE
当缩放选第三个时候，合上笔记本重新打开会出现一个缩放的界面，之后会花屏一下再全屏，这个有办法解决吗？

### ISSUE THREAD

**Issue by fengfst** [xzhih/one-key-hidpi#28]
缩放有四个，分别是1280*720，1440*810，1680*945，1920*1080 ，当缩放选第三个（1440*945）时候，合上笔记本重新打开会出现一个缩放的界面，之后会花屏一下再全屏，这个有办法解决吗？这个问题睡眠唤醒只会是花屏一下，然后正常

**Comment by xzhih** [comment]
注入 edid 试试

**Comment by fengfst** [comment]
尝试了依旧不行，只是第三个位置的选项有问题，不清楚为何

**Comment by xzhih** [comment]
试试这个分辨率 1424x802

**Comment by KivenChen** [comment]
表示同样遇到了这个问题

**Comment by imcsq** [comment]
同样遇到了这个问题，1080P的屏幕，选择最后一个缩放选项的时候就会出问题，关屏后唤醒就只有左上角有个缩放的界面，还会花屏

**Comment by xzhih** [comment]
已更新修复
