### ISSUE TITLE
Works on Mi NB-Air 125 7y30

### ISSUE THREAD

**Issue by influenist** [xzhih/one-key-hidpi#3]
Hi,

Your script is confirmed to be working with Mi NoteBook air. Just 3 issues:

1. On boot the logo keeps scaling up.
1. After wake the screen is scaled top left and the rest remains black.
1. Large text shows high resolution with my monitor, I guess these are incorrect and values need to be adjusted?

<img width="662" alt="screen shot 2018-05-29 at 12 20 46" src="https://user-images.githubusercontent.com/22964559/40653249-e06669ae-633a-11e8-8d66-1518c372d30a.png">

How to fix these?

**Comment by xzhih** [comment]
Inject EDID may help.

**Comment by influenist** [comment]
Hi xzhih. Thanks, for the proposal. I found it didn't resolve the boot issue, wake-up nor Lager text resolution. 

In the source I find:

<key>scale-resolutions</key>
<array>
<data>AAAPAAAACHAA</data>
<data>AAAMgAAABkAA</data>
<data>AAAMgAAABwgA</data>
<data>AAALQAAABlQA</data>
</array>
<key>target-default-ppmm</key>
<real>10.1510574</real>

Which represents:
00000f00 00000870 00 > 3840x2160 no-hidpi
00000c80 00000640 00 > 3200x1600 no-hidpi
00000c80 00000708 00 > 3200x1800 no-hidpi
00000b40 00000654 00 > 2880x1620 no-hidpi

Are these values used at all? As I cannot imagine NB Pro has such a resolutions. When I change it to:

    <data>AAAHgAAABDgA</data>
    <data>AAAGQAAAA4QA</data>
    <data>AAAFoAAAAyoA</data>
    <data>AAAFAAAAAtAA</data>

Meaning:
1920x1080
1600x900
1440x810
1280x720

When rebooting with these values, the Sysctem > Display shows non HIDPI / default screen with no macbook icon. VID and PID are unchanged and showing the same. Is this normal behaviour? It looks like the HiDPI resolutions are generated by macOS itself.

**Comment by influenist** [comment]
Thanks for hinting me on that one (I should have noticed that xD)

10.14 as in beta release or do you mean 10.13.4? Currently I'm on 10.13.3.

**Comment by xzhih** [comment]
lol, my fault, I mean 10.13.4
