### ISSUE TITLE
卸载时找不到bc

### ISSUE THREAD

**Issue by SlippyJimmy** [xzhih/one-key-hidpi#30]
我用后花屏，在Rec卸载时出现了问题，在执行第三步命令 `Vid=$(echo "obase=16;$VendorID" | bc | tr 'A-Z' 'a-z')` 
时，提示找不到 `bc` 命令，这种情况该怎么解决？系统未备份，我不敢继续操作了。

**Comment by xzhih** [comment]
你最好进入系统后运行命令 `sh -c "$(curl -fsSL https://raw.githubusercontent.com/xzhih/one-key-hidpi/master/hidpi.sh)"`，选择 3 进行卸载

进入到 `/Volumes/你的系统盘/System/Library/Displays/Contents/Resources/Overrides`
ls -la 查看最新的那个文件夹，用 rm 命令删除
