### ISSUE TITLE
Screen underscaled after sleep

### ISSUE THREAD

**Issue by tmbt78** [xzhih/one-key-hidpi#33]
Hi,
i've a problem if i use a custom HiDPI resolution (1680*944 HiDPI). When the laptop wake the screen is badly underscaled and it is very small in the top left corner. The rest of the display is black. I can move the mouse but where i see the pointer is not related to where i click and i've to reboot.
If i use the 1440 * 810 HiDPI resolution i don't have this problem.
I already tried injecting edid but still the same problem. Do you know why and what i can do to fix?

**Comment by pro4jhu** [comment]
dell 7580一样的问题，睡眠后显示在屏幕左上角，1680hidpi,大佬有解吗

**Comment by xzhih** [comment]
选择手动输入分辨率 1680x945 1424x802 1280x720 1024x576，回车，然后重启

#16

**Comment by xzhih** [comment]
fixed

**Comment by Shabinder** [comment]
+1 i sm also getting the same issue when i seect 1680x944 hidpi .

I have tried edid too.
Any fix?
Why this issue was closed?

Specs: big sur 11.2.3, hp pavilion gaming 15 1080 display

**Comment by raberraber** [comment]
I have the same issue on my thinkpad t460s with 2560x1440. Tried everything but nothing works

**Comment by m0d16l14n1** [comment]
> I have the same issue on my thinkpad t460s with 2560x1440. Tried everything but nothing works

try that - https://github.com/zysuper/rice-cracker

**Comment by Steini1984** [comment]
> I have the same issue on my thinkpad t460s with 2560x1440. Tried everything but nothing works

did you ever figure this out?

**Comment by sbresin** [comment]
For Kabylake Laptops this person found that using this AAPL,ig-platform-id fixes the issue:
https://github.com/tylernguyen/razer15-hackintosh/blob/master/docs/4_README-POSTinstallation.md
0x59270004 Flags: 0x00E30B0A (Model: Intel Iris Plus Graphics 650)

As I have a i7-10750H with UHD 630, i looked for an Coffee/Cometlake AAPL,ig-platform with the same flags and found this one:
0x3EA50004 Flags: 0x00E30B0A (Model: Intel Iris Plus Graphics 655)

**using it fixes the scaling issue**

As i have only the Internal Display wired to the IGPU, i am now using 0x3E9B0008 (UHD 630 with only 1 connector) and patch only the Flags to 0x00E30B0A and i do not have the underscaling issue anymore. This is how it looks like in OpenCore DeviceProperties for the IGPU:
```
<key>framebuffer-flags</key>
<data>CgvjAA==</data>
<key>framebuffer-patch-enable</key>
<data>AQAAAA==</data>
```

When i compare the flags with the default for laptops (0x3EA50009) only these 2 flags were missing, so using one of these seems to be the fix:
FBUnknownFlag400000
FBEnableDynamicCDCLK
