### ISSUE TITLE
睡眠后唤醒分辨率会错乱，只有左上角显示整个屏幕，鼠标位置错乱，关闭HIDPI所有方法失效。

### ISSUE THREAD

**Issue by fawoo** [xzhih/one-key-hidpi#35]
目前所有办法无法关闭HIDPI，设置内选择“较大文字”是开启以前的状态，其他的选了也全是错的。开机没有超大苹果。

**Comment by xzhih** [comment]
如果看了恢复教程还没恢复，就只能是你自己的问题了
https://github.com/xzhih/one-key-hidpi/blob/master/README-zh.md#%E6%81%A2%E5%A4%8D

**Comment by fawoo** [comment]
可能，因为备份的数据里面没有之前备份成功的内容，如果我去找别人要一份同机型的备份文件，可以正常恢复吗？

**Comment by xzhih** [comment]
嗯

**Comment by xzhih** [comment]
已更新修复
