### ISSUE TITLE
终端提示开启成功，但是用RDM调整并没有开启HIDPI

### ISSUE THREAD

**Issue by MicroKou** [xzhih/one-key-hidpi#36]
![image](https://user-images.githubusercontent.com/28616429/53713239-2bec7500-3e85-11e9-99dc-a9f205596b8a.png)

**Comment by xzhih** [comment]
试试这条命令 `sudo defaults write /Library/Preferences/com.apple.windowserver DisplayResolutionEnabled -bool YES`

**Comment by MicroKou** [comment]
> 试试这条命令
> 
> ```shell
> sudo defaults write /Library/Preferences/com.apple.windowserver DisplayResolutionEnabled -bool YES
> ```

可以了，感谢！

**Comment by basten1899** [comment]
我只有1680x944 可以hiDPI
