### ISSUE TITLE
10.14.3开启后没有合适的分辨率

### ISSUE THREAD

**Issue by taoloveo** [xzhih/one-key-hidpi#37]
![jietu20190305-152623](https://user-images.githubusercontent.com/26987363/53787869-1ba6c980-3f5b-11e9-9c00-1452ac6139bc.jpg)

之前10.14.1可以正常开启，重新安装14.3后1600*900不显示为高分辨率，脚本和小兵大佬提供的教程也不出现

**Comment by xzhih** [comment]
是MacOS的显卡驱动调整，这个我没法弄，如果你是kabylake，可以仿冒skylake(1916)

**Comment by taoloveo** [comment]
> 是的MacOS的显卡驱动调整，这个我没法弄，如果你是kabylake，可以仿冒SKYLAKE微架构（1916）

这个如果我降到10.13的话可以正常开启吧

**Comment by xzhih** [comment]
10.13.6也需要仿冒才能开启1600x900,1680x945这样的，不仿冒的可以开启1440x810

**Comment by Chakid** [comment]
> 是MacOS的显卡驱动调整，这个我没法弄，如果你是kabylake，可以仿冒skylake(1916)

问下我的是kabylake，HD630,也是没有1600x900,但是您说的skylake(1916)不怎么懂，大佬能提示一下不

**Comment by Chakid** [comment]
> 是MacOS的显卡驱动调整，这个我没法弄，如果你是kabylake，可以仿冒skylake(1916)

![image](https://user-images.githubusercontent.com/29879464/55208879-e66c5f00-521a-11e9-9c34-543f00be7c77.png)
我看黑果小兵博客里面没有这个1916的

**Comment by xzhih** [comment]
@Chakid 

仿冒，就是让你的黑苹果把 kabylake 的显卡识别为 skylake 的，这样可以加载 skylake 的显卡驱动，解决模糊过渡不自然的问题

以及 1600x900 的 hidpi （用脚本时选择手动输入：1680x944 1600x900 1440x810 1280x720）

仿冒教程：

首先，设置启动参数 lilucpu=8

然后，注入显卡信息

你可以直接在hackintool里设置
CPU架构: skylake, 平台ID: 0x19160000, 设备ID: 0x1916
然后导出到 EFI 就好

或者，直接修改config.plist，Devices -> Properties -> PciRoot(0x0)/Pci(0x2,0x0)
把 AAPL,ig-platform-id 的值改为 <00001619>
把 device-id 的值改为 <16190000>

保存，重启就可以了

已知副作用：HEVC(h265) 硬解失效

**Comment by Chakid** [comment]
哇，谢谢你的细心指导，我本来是7代HD630，然后换成你说的 skylake的，然后显卡没驱动成功，直接7MB，然后我再换成kabylake的平台，这个时候就可以了
![image](https://user-images.githubusercontent.com/29879464/55234771-cfebf500-5266-11e9-9391-5c84caa649bf.png)
再次感谢你的回答

**Comment by xzhih** [comment]
外置显示器好像一直都可以吧，内置的要仿冒

**Comment by Chakid** [comment]
> 外置显示器好像一直都可以吧，内置的要仿冒

嗯，我内置的那么弄也好了

**Comment by InkJiang** [comment]
> 哇，谢谢你的细心指导，我本来是7代HD630，然后换成你说的 skylake的，然后显卡没驱动成功，直接7MB，然后我再换成kabylake的平台，这个时候就可以了
> ![image](https://user-images.githubusercontent.com/29879464/55234771-cfebf500-5266-11e9-9391-5c84caa649bf.png)
> 再次感谢你的回答

你好，我的换了之后变得特别卡，然后再换回来又变成1080p了。请教一下。
