### ISSUE TITLE
10.13.6没有效果不知道是不是打开方式不对

### ISSUE THREAD

**Issue by linkimfly** [xzhih/one-key-hidpi#38]
10.13.6黑苹果 根据教程步骤都正确设置了，但是并没有效果。
显示器27寸。
sudo defaults write /Library/Preferences/com.apple.windowserver DisplayResolutionEnabled -bool YES 执行过了，
ISP也是禁用状态了，

**Comment by xzhih** [comment]
有没有错误提示

**Comment by linkimfly** [comment]
没有错误提示

**Comment by xzhih** [comment]
用RDM打开也没有选项？

**Comment by linkimfly** [comment]
我在其他Issuse看到你说显示器接口要用DP？难道是因为这个问题吗？我是HDMI接口

**Comment by xzhih** [comment]
接口倒没太大关系

**Comment by linkimfly** [comment]
RDM打开都不带闪电的，我试过在这里手动生成配置 手动替换，
链接：https://comsysto.github.io/Display-Override-PropertyList-File-Parser-and-Generator-with-HiDPI-Support-For-Scaled-Resolutions/ 
1080P能显示闪电，但是开没开一个样，并没有效果

**Comment by xzhih** [comment]
可能是显卡驱动问题吧，这个不好找原因

**Comment by linkimfly** [comment]
跟显卡不知道会不会有关系呢，显示是GTX970 装的WebDriver-387.10.10.10.40.105.pkg 驱动
