### ISSUE TITLE
10.14.3 hd4600笔记本外接4k显示器问题

### ISSUE THREAD

**Issue by Ezioer** [xzhih/one-key-hidpi#39]
使用脚本开启后，在关于本机-显示器 外接显示器显示有误 27寸的显示器变成了61寸，后面的分辨率显示是正确的，系统报告中外接显示器显示分辨率是4k ui看起来类似1080，用RDM可以看到1920X1080旁边是有闪电图标的 也就是开启了hidpi，但是显示效果依然有些糊，这是为什么？

**Comment by xzhih** [comment]
4K显示器不是自动打开hidpi的吗，不需要这个脚本

**Comment by Ezioer** [comment]
> 4K显示器不是自动打开hidpi的吗，不需要这个脚本

我的没有打开，我是用hdmi连接显示器的，好像用dp线就会自动打开hidpi，无奈笔记本没有dp接口，开启1080的hidpi显示效果跟没开启hidpi的1080显示效果是一样的，但是720的hidpi就有效，显示效果有显著的提升，为什么1080的hidpi开启跟不开启一样的效果，想不通这点

**Comment by xzhih** [comment]
这个我也不太了解
