### ISSUE TITLE
10.14不生效

### ISSUE THREAD

**Issue by cv0cv0** [xzhih/one-key-hidpi#4]

**Comment by xzhih** [comment]
关闭SIP试试，我这边是生效的

**Comment by cv0cv0** [comment]
是黑苹果，SIP默认关闭。

发自我的 iPhone

**Comment by xzhih** [comment]
那只能是其他问题了，等10.14正式版出来在试试

**Comment by stevezhengshiqi** [comment]
我这边也生效，试试删除Display文件夹下相应的文件夹再重装吧。

**Comment by zjplus** [comment]
请问下问题解决了吗？我也是黑苹果，修改了配置重启都不生效

**Comment by cv0cv0** [comment]
@zjplus 用https://github.com/syscl/Enable-HiDPI-OSX生效了。

**Comment by xzhih** [comment]
现在应该可以了
