### ISSUE TITLE
mojave白苹果外接2k、黑苹果1080p开启均没有效果

### ISSUE THREAD

**Issue by TrainTsang** [xzhih/one-key-hidpi#42]
不知道原因何在，没有任何错误提示

**Comment by xing634325131** [comment]
![image](https://user-images.githubusercontent.com/3675673/57266650-7bcb0080-70af-11e9-821a-c5d797c8fe39.png)
没有效果

**Comment by xzhih** [comment]
白果记得关闭SIP

**Comment by TrainTsang** [comment]
> 白果记得关闭SIP

是的，后来用别的工具+关闭SIP解决了
