### ISSUE TITLE
先谢谢大佬，横屏的时候一键弄好了，但是切换成竖屏是有复原了

### ISSUE THREAD

**Issue by strivecheng** [xzhih/one-key-hidpi#43]
竖屏的时候应该怎么操作呢？不是同一个显示器，怎么竖屏的时候就复原了，麻烦，大佬告知一下

**Comment by xzhih** [comment]
竖屏的选择手动输入分辨率，手动输入你要的分辨率，比如 1080x1920 等等

**Comment by leafleave** [comment]
如果需要经常旋转显示器怎么办。。比如我。。

**Comment by xzhih** [comment]
旋转后可以在设置里选择缩放分辨率的啊，也是 hidpi 的
