### ISSUE TITLE
一直没有权限，写入不了

### ISSUE THREAD

**Issue by strivecheng** [xzhih/one-key-hidpi#44]
<img width="796" alt="QQ20190423-225936@2x" src="https://user-images.githubusercontent.com/20623884/56591561-8f8c5680-661b-11e9-9016-9fe60217dee8.png">
大佬看看是什么问题，不能开启1080，没有小火箭

**Comment by xzhih** [comment]
在  `系统信息.app` 里点击软件这一项，看看 `系统完整性保护` 是不是关闭了

**Comment by strivecheng** [comment]
> 在 `系统信息.app` 里点击软件这一项，看看 `系统完整性保护` 是不是关闭了

是已启动状态啊

**Comment by xzhih** [comment]
要停用啊，启用了就没权限了

**Comment by strivecheng** [comment]
所有都成功了，看那个文件夹下，文件夹也生成了，就是不成功啊。用RDM查看1080 的没有小闪电啊！我用脚本成功之后，重启电脑之后logo没有变大

**Comment by xzhih** [comment]
1080p的显示器开1080P的hidpi？这有什么意义？增加显卡负载好玩？

**Comment by strivecheng** [comment]
我显示器是2k的啊，就是字体太小，我想改成1080的，清晰度不变，字体变大啊

**Comment by xzhih** [comment]
咦？那你选2K显示器也不行吗，接口是HDMI？不过我也是HDMI，是可以1080p hidpi的。
你试试手动输入分辨率那个选项，输入几个大点的分辨率试试

**Comment by strivecheng** [comment]
我的也是HDMI接口啊。好的，我再试试手动输入分辨率看看，大佬，能加个微信吗？方便请教一下

**Comment by strivecheng** [comment]
我的微信号xcc2734

**Comment by strivecheng** [comment]
大佬，手动输入的，小闪电出来啦！！！谢谢！
