### ISSUE TITLE
报错：sed: 1: "s:EDid:AP///////wBNEEkU ...": unescaped newline inside substitute pattern

### ISSUE THREAD

**Issue by rocymp** [xzhih/one-key-hidpi#45]

**Comment by xzhih** [comment]
完整点，截图发出来

**Comment by rocymp** [comment]
_    _   _____   _____    _____    _____
 | |  | | |_   _| |  __ \  |  __ \  |_   _|
 | |__| |   | |   | |  | | | |__) |   | |
 |  __  |   | |   | |  | | |  ___/    | |
 | |  | |  _| |_  | |__| | | |       _| |_
 |_|  |_| |_____| |_____/  |_|      |_____|

============================================
Password:

(1) Enable HIDPI
(2) Enable HIDPI (with EDID)
(3) Disable HIDPI

Enter your choice [1~3]: 2
------------------------------------
|********** Choose Icon ***********|
------------------------------------
(1) iMac
(2) MacBook
(3) MacBook Pro
(4) LG Display
(5) Remain as it is

Enter your choice [1~5]: 3
------------------------------------------
|********** resolution config ***********|
------------------------------------------
(1) 1080P Display
(2) 2K Display
(3) Manual input resolution

Enter your choice: 1
sed: 1: "s:EDid:AP///////wBNEEkU ...": unescaped newline inside substitute pattern
Enabled, please reboot.
Rebooting the logo for the first time will become huge, then it will not be.

**Comment by rocymp** [comment]
![image](https://user-images.githubusercontent.com/7627227/58032876-0e5eab80-7b56-11e9-9c44-5bd09192d9f2.png)

**Comment by xzhih** [comment]
你是不是装了 gnu-sed

**Comment by overminder** [comment]
我的第一反应和gnu-sed也有关，但是我并没有alias gsed sed。debug了一下，发现原因是因为`function enable_hidpi_with_patch`中的`$EDid`包含回车，而这是因为前面的`base64`的输出中包含回车。我把`base64`改成`base64 -w 0`就好了。
