### ISSUE TITLE
脚本使用的问题

### ISSUE THREAD

**Issue by pexcn** [xzhih/one-key-hidpi#46]
你好，对于这个脚本我有一些疑问：
在选择要显示的 ICON 那里，选择不同选项会有什么区别？保持原样又是什么意思？
此外还有这个疑问：https://github.com/xzhih/one-key-hidpi/commit/35d80ce18b32bc065ec7ca71cf8d275406255cf7#r33416997

**Comment by xzhih** [comment]
icon随意，只是改变了设置里的图片外挂，其他没差，保持原样就是你没用脚本之前图标是怎样就怎样，和smbios设置的机型有关

1600x900 这个分辨率有时是开不了的（有时显卡仿冒可以开启），想用这个分辨率可以选择选项3，手动输入打开

1680x945 也是有时开不了，换上1680x944就可以

但是很多时候建议用手动输入的

**Comment by pexcn** [comment]
好的，感谢解答。
手动最多可以输入几档？如果我只想要 1600x900，1440x810，1280x720 这三档分辨率，我只要在手动那里输入这三个就可以了吗？

**Comment by xzhih** [comment]
是的，你想输入多少都行，但是不一定能开得起来

**Comment by pexcn** [comment]
好的，谢谢，有空再试试

**Comment by pexcn** [comment]
另外还想问一下作者 @xzhih 注入EDID和不注入有什么区别？推荐注入吗？

**Comment by xzhih** [comment]
有些显示器强行开启hidpi之后出现闪屏或者内建显示器黑屏的问题，可以注入EDID来解决
并且我注入的这个EDID是修改过的，可能可以解决一些比如色偏、无法调节内建显示器亮度的问题

我的建议是没有问题就不注入，遇到问题可以尝试注入

黑苹果笔记本外接低分辨率显示器的时候，建议内建外接都注入

**Comment by pexcn** [comment]
我要遇到个问题，无论注入还是不注入，开启 HiDPI 之后亮度都无法保存，重启之后还是最高亮度

**Comment by xzhih** [comment]
亮度是你的显卡驱动问题
