### ISSUE TITLE
Mac mini (Late 2012) 外接1080P显示器 无效果

### ISSUE THREAD

**Issue by xywf221** [xzhih/one-key-hidpi#48]
mac系统版本:`10.14.4`
sip状态:`关闭`
显示器:`DELL SE2416HM 1920*1080`
命令行执行步骤:开启hidpi,mac pro logo
重启进入 -> 系统偏好设置 -> 显示器 发现没有效果

**Comment by xzhih** [comment]
那就只能用 RDM 来选择分辨率了，http://avi.alkalay.net/software/RDM/RDM-2.2.dmg

**Comment by xywf221** [comment]
> 那就只能用 RDM 来选择分辨率了，http://avi.alkalay.net/software/RDM/RDM-2.2.dmg

感谢回复，已经使用其他方法+rdm开启hidpi了

**Comment by EnjoyColin** [comment]
> > 那就只能用 RDM 来选择分辨率了，http://avi.alkalay.net/software/RDM/RDM-2.2.dmg
> 
> 感谢回复，已经使用其他方法+rdm开启hidpi了

求问是怎么操作的啊？
