### ISSUE TITLE
笔记本可以开启，台式机只多了分辨率选项，没有⚡️标识

### ISSUE THREAD

**Issue by dushicai** [xzhih/one-key-hidpi#49]
![屏幕快照 2019-05-15 15 05 26](https://user-images.githubusercontent.com/16698336/57755230-e7057a00-7722-11e9-9b5a-20bc92434d35.png)
![屏幕快照 2019-05-15 15 03 59](https://user-images.githubusercontent.com/16698336/57755233-ea006a80-7722-11e9-82ce-30e24a43f207.png)

**Comment by xzhih** [comment]
用 RDM 没有⚡️标志？
是用的 DP 接口的吗，目前得到的反馈是，DP->DP、HDMI->HDMI可以，像 DP->HDMI 就很可能不行

**Comment by dushicai** [comment]
用的hdmi接口
RDM安装后，连RDM分辨率选项icon都没有
![屏幕快照 2019-05-16 14 40 45](https://user-images.githubusercontent.com/16698336/57831773-9d7f6280-77e8-11e9-9bbc-d2dab3ad5a88.png)

**Comment by dushicai** [comment]
显示器：分辨率是1080p AOC，
分辨率设置成1080p 显示器设置成“保持原样”就没有任何选项
分辨率设置成2K 显示器设置成“MacBook Pro”选项出来了
这样设置可以吗，有没有副作用？
另外尝试过“开启HIDPI（同时注入EDID”开不了机，用了你推荐的那种方式恢复的

**Comment by TomHeaven** [comment]
妙计！设置成2K屏确实可以, 1080p不行。我也是台式机。

**Comment by dushicai** [comment]
貌似动画掉帧，感觉卡卡的。

**Comment by xzhih** [comment]
> 显示器：分辨率是1080p AOC，
> 分辨率设置成1080p 显示器设置成“保持原样”就没有任何选项
> 分辨率设置成2K 显示器设置成“MacBook Pro”选项出来了
> 这样设置可以吗，有没有副作用？
> 另外尝试过“开启HIDPI（同时注入EDID”开不了机，用了你推荐的那种方式恢复的

没有副作用

**Comment by xzhih** [comment]
> 貌似动画掉帧，感觉卡卡的。

显卡不给力吧，hidpi是2x分辨率
