### ISSUE TITLE
分辨率配置

### ISSUE THREAD

**Issue by JunFreeman** [xzhih/one-key-hidpi#50]
<img width="404" alt="Xnip2019-05-15_20-09-10" src="https://user-images.githubusercontent.com/14955364/57774527-5728f580-774d-11e9-9d6e-1b1a5c65d717.png">

如上图 这个分辨率配置是写当前外置显示器的分辨率 还是指要缩放的分辨率

**Comment by JunFreeman** [comment]
<img width="492" alt="Xnip2019-05-15_20-11-14" src="https://user-images.githubusercontent.com/14955364/57774650-aa02ad00-774d-11e9-9bcd-d0815ddc5024.png">
另外我的外置显示器是LG 红框位置选择MacBook 和选择LG显示器有什么区别么

**Comment by xzhih** [comment]
1. 当前外置显示器的分辨率
2. 这个选项会反映到（设置 -> 显示器）这里的显示器样式
