### ISSUE TITLE
开启HIDPI模式后 巨大logo重启也一样巨大

### ISSUE THREAD

**Issue by HappyLeiLei** [xzhih/one-key-hidpi#51]
开启HIDPI模式后 巨大logo重启也一样巨大 😂
macOS 10.14.4  
ThinkPad E550

**Comment by xzhih** [comment]
如果是2倍放大就是正常的，这个只能换白果解决

**Comment by HappyLeiLei** [comment]
哦哦 那明白了 非常感谢你的回复  给你的程序点个赞




------------------ 原始邮件 ------------------
发件人: "ZeRo Xu"<notifications@github.com>; 
发送时间: 2019年5月28日(星期二) 下午2:55
收件人: "xzhih/one-key-hidpi"<one-key-hidpi@noreply.github.com>; 
抄送: "Happy磊"<444500064@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [xzhih/one-key-hidpi] 开启HIDPI模式后 巨大logo重启也一样巨大 (#51)




如果是2倍放大就是正常的，这个只能换白果解决
 
&mdash;
