### ISSUE TITLE
如何计算可以用的分辨率？

### ISSUE THREAD

**Issue by 0x112** [xzhih/one-key-hidpi#52]
在mojave上，无论注入或者不注入EDID，睡眠唤醒之后都会花屏和1/4屏，但是根据这里所说的https://github.com/xzhih/one-key-hidpi/issues/28#issuecomment-452320723 使用 1424x802 这个分辨率，会显示正常。但是我想再把这个分辨率再调高一些，到1600x900附近，请问怎么计算接近这个数值的分辨率？

**Comment by xzhih** [comment]
最简单的方法 -> 计算器

**Comment by 0x112** [comment]
应该怎样计算呢？1424x802 这个数值是怎样得出来的？

**Comment by xzhih** [comment]
这是群里小伙伴试出来的

**Comment by 0x112** [comment]
好吧，看来是要慢慢试了。。

**Comment by strivecheng** [comment]
> 这是群里小伙伴试出来的

怎么进群啊
