### ISSUE TITLE
我遇到一个很奇怪的问题，我怀疑此脚本与Adobe有冲突

### ISSUE THREAD

**Issue by Ziloong** [xzhih/one-key-hidpi#53]
我的系统是macOS 10.14.5  非白苹果
我在一个全新做好的系统里面，装好Adobe的PS Ai AE Pr Au，然后运行此脚本 开启HIDPI注入花屏补丁，重启完毕后，adobe的全部东西全部打不开（包括adobe install、adobe uninstall）

为确定此问题，我做了一个小测试。在一个全新的系统里面，我先完善好所有的驱动，比如触摸板、显卡、CPU、网卡的驱动，然后测试了一下 是否还能打开adobe，结果毫无疑问都是运行正常。  然后我运行此HIDPI脚本，开启HIDPI没有注入花屏补丁重启 adobe的东西都是正常的。 一但我注入花屏补丁，adobe的所有东西都不正常了。

难道我这个是个例？非常的奇怪。 
我执行
`ls / Volumes /
 cd / Volumes /你的系统盘/系统/库/显示/内容/资源/覆盖
EDID =（$（ ioreg -lw0 | grep -i “ IODisplayEDID ”  | sed -e “ / [^ <] * </ s /// ” - e “ s / \> // ”）））
Vid =（$（ echo $ EDID  | cut -c18-20 ））
rm -rf ./DisplayVendorID- $ Vid 
cp -r ./HIDPI/backup/ * ./`

也都毫无作用。

**Comment by xzhih** [comment]
用脚本自带的关闭命令来关闭试试，如果你看过脚本也看得懂的话，里面并没有修改什么关键的系统的文件。
你这个启动不了我不排除是adobe检测到了系统文件的更改？或者是说分辨率的更改？再或者是发现了是虚假的分辨率？

**Comment by Ziloong** [comment]
抱歉，因为我从事的是设计工作，对脚本不太了解。
我尝试过使用脚本的卸载命令但是这个并没有效果，除了重装macOS并无他法。

但是如果我手动注入EDID和开启HIDPI，adobe全家桶都不会出现问题。
我重装了6次系统了，因为昨晚一个巧合所以发现这个冲突，后来也验证了一下我的想法。

**Comment by xzhih** [comment]
我无法复现你说的这个问题，这个issue留着打开吧，估计也有其他人遇到，大家讨论看看哪里出的问题
