### ISSUE TITLE
在外接显示器显示信号源为1080P

### ISSUE THREAD

**Issue by tvvo** [xzhih/one-key-hidpi#54]
大神你好！感谢你写的sh，她已经帮到了很多人。

但是我在通过控制台操作成功之后(系统保护已停用)，设置中只有HiDPI最高只有：960x540；非HiDPI只有1920x1080
通过RDM设置为高分辨之后，显示模糊。并且显示器OSD中显示输入源依旧为1920x1080。
请问未能成功设置，是因为我的设置没对还是硬件不支持？望解答

配置如下：
显示器：翔野XE2400 (小厂)
分辨率：3840x2160
Macbook Air：11寸 2012年中款
CPU：Core i5 1.7Ghz
内存：4GB
显卡：HD 4000 1535MB
macOS：10.14.4
视频线：淘宝买的戴尔DP线(Surface Pro 3完全能输出4K分辨率)

**Comment by xzhih** [comment]
你去查一查你的MacBook支持4k分辨率吗，我记得hd4000默认好像是不支持的，然后找找看有没有强行打开支持的方法

**Comment by tvvo** [comment]
> 你去查一查你的MacBook支持4k分辨率吗，我记得hd4000默认好像是不支持的，然后找找看有没有强行打开支持的方法

感谢回复。所以如果MacBook支持4k，正常情况输出到显示器就是4k分辨率对吗？
