### ISSUE TITLE
开启HIDPI后144Hz选项消失

### ISSUE THREAD

**Issue by braisedcat** [xzhih/one-key-hidpi#55]
10.13.6系统，开启前是可以144Hz的。

**Comment by xzhih** [comment]
要用144还是把hidpi关掉吧

**Comment by kyler719** [comment]
这两个功能真的不能并存吗。。。。。很难受啊

**Comment by kyler719** [comment]
> 要用144还是把hidpi关掉吧

大佬无解么？

**Comment by xzhih** [comment]
hidpi是2倍缩放，可能是系统没法在这样的高分辨率下支持144

**Comment by szhu3210** [comment]
发现了一个可行的办法，先用这个一键开启的脚本开启HiDPI，然后用SwitchResX创建一个custom的分辨率，里面填144Hz（或任意值，只要显示器支持就行），保存好以后重启，就可以在设置里看到各种分辨率了。（这个方法的缺点就是要费点钱）
<img width="663" alt="Screen Shot 2020-07-24 at 4 19 01 PM" src="https://user-images.githubusercontent.com/23638183/88442450-6b449a00-cdc9-11ea-96d4-611392817e1f.png">

**Comment by GTGraphics3** [comment]
发现一个更可行的方法：
尝试手动输入分辨率
`1680x945 3360x1890`
（手动输入UI看起来的分辨率，和x2的分辨率）
重启后在系统偏好设置里，按住alt点缩放，可以选择1680x945@144了
