### ISSUE TITLE
10.15 catalina 权限问题

### ISSUE THREAD

**Issue by qiyongsen** [xzhih/one-key-hidpi#57]
更新了10.15测试版，然后即便SIP disabled也没有权限，整个/System目录变成了 read only file system

**Comment by monsteryip** [comment]
me too

**Comment by monsteryip** [comment]
凉了凉了,按现在策略怕是没办法了

https://www.apple.com/macos/catalina-preview/features/

![image](https://user-images.githubusercontent.com/16128228/60177466-8aca6580-984b-11e9-949b-5f5e0108e56e.png)

**Comment by yangjichen** [comment]
楼上的兄弟，我也好难过啊，手贱中午升级的，后悔

**Comment by xzhih** [comment]
挂载一下根目录，再运行脚本试试，
`mount -uw /`
一直没空管这些，周末我更新一下

**Comment by stevezhengshiqi** [comment]
@xzhih 这个方法适用于我的机子，感谢。

**Comment by yangjichen** [comment]
我不太行，报错Failed to stat file //AppleInternal, error No such file or directory
@stevezhengshiqi

**Comment by stevezhengshiqi** [comment]
@yangjichen 可以忽略这行，不影响脚本运行

**Comment by xzhih** [comment]
@yangjichen 运行 `sudo mount -uw /` 后，再重启访达进程 `killall Finder`，这样看看还有没有报错

**Comment by yangjichen** [comment]
@xzhih @stevezhengshiqi 确实是可以的！谢谢！

**Comment by xzhih** [comment]
在我还没更新脚本前，先保留这个 issues，让需要的人看到

**Comment by laradong** [comment]
macOS Mojave 10.14.5 执行出错 Operation not permitted

**Comment by stevezhengshiqi** [comment]
@laradong 首先，10.14.5没必要执行这个命令；其次，检查一下代码前是否加了sudo

**Comment by funnybones2015** [comment]
> 在我还没更新脚本前，先保留这个 issues，让需要的人看到

这种方法能正常开启了，但是重启或关机时屏幕会花屏。望修复~

**Comment by JohnnyJinn** [comment]
之前看到的solution都不太行，等脚本更新了

**Comment by insoz** [comment]
感谢, 果断star 了

**Comment by xzhih** [comment]
已更新

**Comment by FateLight** [comment]
@xzhih 有效，10.15 beta 5

**Comment by lhy920816** [comment]
> 已更新

请问具体如何操作呢？

**Comment by laixintao** [comment]
感谢，这个issue救我一命。
