### ISSUE TITLE
白苹果对外接显示器开启hidpi , 并选择icon后 , 笔记本内建显示器的icon会被覆盖

### ISSUE THREAD

**Issue by IdeaManYu** [xzhih/one-key-hidpi#58]
白苹果对外接显示器开启hidpi , 并选择icon后 , 笔记本内建显示器的icon会被覆盖
内建显示器的icon会被覆盖为电视显示器

**Comment by xzhih** [comment]
`Icons.plist` 一年没更新了，缺少新的白苹果配置，等 10.15 出来我一起更新

**Comment by IdeaManYu** [comment]
> `Icons.plist` 一年没更新了，缺少新的白苹果配置，等 10.15 出来我一起更新

嗯嗯 , 10.15的sip策略貌似改了 , 这个玩法可能玩不下去了

**Comment by IdeaManYu** [comment]
> `Icons.plist` 一年没更新了，缺少新的白苹果配置，等 10.15 出来我一起更新

嗯嗯 , 10.15的sip策略貌似改了 , 这个玩法可能玩不下去了

**Comment by xzhih** [comment]
不用担心，有解的

**Comment by xzhih** [comment]
已更新
