### ISSUE TITLE
我的没报错但是生成的文件不对

### ISSUE THREAD

**Issue by Kntt** [xzhih/one-key-hidpi#6]
![image](https://user-images.githubusercontent.com/20291026/44596561-33103780-a7ff-11e8-80e8-15f87bb741b6.png)
![image](https://user-images.githubusercontent.com/20291026/44596585-4cb17f00-a7ff-11e8-8ad9-9ab9511d9ab8.png)
提示成功了 但是生成的文件
感觉是没读出来pid 和 vid 还有edid

**Comment by Kntt** [comment]
bash 不熟， 看个大概

**Comment by xzhih** [comment]
现在应该可以了，没注意看，今天又老铁提交了
