### ISSUE TITLE
开机时第二阶段logo巨大或者闪屏

### ISSUE THREAD

**Issue by phenixcxz** [xzhih/one-key-hidpi#62]
hd4600显卡，1080分辨率，试了好几次有两种可能
1.开机logo变得巨大，应该是720分辨率下的logo,关机屏幕下方五分之一左右会闪屏，从左到右的条状白线
2.开机logo第一次变得巨大，第二次及以后稍大，但是在第二次及以后图标稍微放大前屏幕会出现8苹果，且关机和第一种状况一样闪屏

**Comment by xzhih** [comment]
1. 新增了一个选项，可以设置 1424x802 的分辨率，这个可以解决关机或睡眠后屏幕显示缩小或闪屏的问题。

2. 开机 logo 变大这个问题没办法解决，因为分辨率是假的，8 苹果与脚本无关，你去搜一下开机 8 苹果的相关解决办法
