### ISSUE TITLE
能否支持1680*945的分辨率，1424感觉字体偏大了

### ISSUE THREAD

**Issue by chengjianhao** [xzhih/one-key-hidpi#63]
手动添加hidpi分辨率再用rdm开启1680*945的分辨率会导致睡眠后局部闪屏雪花屏，这是mojave系统不支持还是这个方法存在问题，如果系统支持的话，求助能否开发一个新版本，通过脚本设置这个分辨率。

**Comment by xzhih** [comment]
脚本内置了，如果没法在系统里选择这个分辨率，那我也没办法

**Comment by GreenTeodoro839** [comment]
> 脚本内置了，如果没法在系统里选择这个分辨率，那我也没办法

但是1680x945并不是hidpi分辨率，而是直接降低了分辨率
