### ISSUE TITLE
1920*1200内屏 无法开启1600*1000 或者1440*900的分辨率

### ISSUE THREAD

**Issue by rhtect** [xzhih/one-key-hidpi#64]
你好 我是联想 miix520机器 1920*1200内屏 无法开启1600*1000 或者1440*900的分辨率

**Comment by xzhih** [comment]
先执行这个命令

```bash
sudo defaults write /Library/Preferences/com.apple.windowserver DisplayResolutionEnabled -bool YES
```

然后在运行脚本，选择手动输入

```
1680x1050 1440x900 1280x800 1024x640
```

这样应该就能在系统设置里选择相应的分辨率了

如果实在需要 1600x1000 这一档，可以在上面的 1680x1050 后面添加

但是这样的话，可能没法在系统设置里选择，你需要使用 [RDM](http://avi.alkalay.net/software/RDM/RDM-2.2.pkg) 来选择

**Comment by rhtect** [comment]
谢谢 还是没有这个分辨率
RDM智能显示 1280*800的hidpi

不知道会不会是内置显示器的问题呢

smbios 设置成macbook pro

**Comment by xzhih** [comment]
确保注入正确的显卡ID

**Comment by rhtect** [comment]
uhd 630
 i7 8550 的核心显卡 自动识别的

按住alt打开隐藏分辨率设置后 RDM 可以识别其他比例的HIDPI分辨率 唯独没有16:10的选项

**Comment by xzhih** [comment]
应该是脚本内注入的分辨率梯度不适合16:10，周末有空我更新一下，增加一个选项，到时候你再来看看

**Comment by rhtect** [comment]
好的 谢谢
3:2的可以吧

**Comment by xzhih** [comment]
3:2 什么分辨率

**Comment by rhtect** [comment]
2560*1700
3000*2000
1600*1065

**Comment by chengjianhao** [comment]
测试一下会不会睡眠后闪屏

**Comment by xzhih** [comment]
我已经提交到 dev 分支了
你可以执行下面的命令使用

```bash
sh -c "$(curl -fsSL https://raw.githubusercontent.com/xzhih/one-key-hidpi/dev/hidpi.sh)"
```

我手头没有相应的显示器调试，所以只能你来试了，不能保证能达到你要的效果

**Comment by wdrich** [comment]
你好 我回去测试一下 给您反馈

**Comment by rhtect** [comment]
你好 试了一下 还是没有成功
