### ISSUE TITLE
关闭SIP后开启HIDPI后，再次开启SIP, HIDPI还是生效的么

### ISSUE THREAD

**Issue by muddySu** [xzhih/one-key-hidpi#65]
关闭SIP后开启HIDPI后，再次开启SIP, HIDPI还是生效的么

**Comment by xzhih** [comment]
生效

**Comment by xianyu-ing** [comment]
> 关闭SIP后开启HIDPI后，再次开启SIP, HIDPI还是生效的么

你是如何关闭 SIP 的？

**Comment by cv0cv0** [comment]
@xianyu-ing csrutil enable

**Comment by xzhih** [comment]
开启：`csrutil enable`
关闭：`csrutil disable`
查看当前状态：`csrutil status`
