### ISSUE TITLE
启用后高斯模糊效果出现问题，出现不连续的分层

### ISSUE THREAD

**Issue by bingcheng1998** [xzhih/one-key-hidpi#66]
在未开启hidpi之前，系统的启动台与自带一系列APP的上部分的条状带的模糊效果没有分层。
---
在开启后程序的**条状部分**高斯模糊效果分层：
![image](https://user-images.githubusercontent.com/26592478/63436517-6958b500-c45b-11e9-8f2c-aa018d9b9e3e.png)
---
**启动台**的高斯模糊也会分层
![image](https://user-images.githubusercontent.com/26592478/63436826-fc91ea80-c45b-11e9-9dcc-11472c89f7a8.png)
---
希望可以找出解决办法。**谢谢！**

**Comment by xzhih** [comment]
我之前用的笔记本核显是 hd620 直接原生驱动就会出现高斯模糊过渡不自然的情况，然后对核显进行仿冒 hd520 就可以了，但是这样就不能 HEVC 硬解，你可以去参考一下： https://github.com/xzhih/dell-7460-7560-hackintosh

光是这个脚本的话，没办法处理这个问题，我也有尝试过修改 EDID 等方法

**Comment by bingcheng1998** [comment]
> 我之前用的笔记本核显是 hd620 直接原生驱动就会出现高斯模糊过渡不自然的情况，然后对核显进行仿冒 hd520 就可以了，但是这样就不能 HEVC 硬解，你可以去参考一下： https://github.com/xzhih/dell-7460-7560-hackintosh
> 
> 光是这个脚本的话，没办法处理这个问题，我也有尝试过修改 EDID 等方法

谢谢你。事实上我是白苹果。这个是外界屏幕开启hidpi之后才有的缺陷，内建的没有这个问题，不开启hidpi也不会有这个问题。不知道白苹果怎么解决。

**Comment by xzhih** [comment]
这个我就不清楚了，我用白果没遇到过这个问题，2015款的 MBP 使用 HDMI 连接和 mDP 连接都没有遇到。

尝试在开启的时候选择注入 EDID，如果还是没有效的话，没办法了

对了，你上面截图是看不出的，只是在显示器显示的时候会有过渡效果不自然的问题

所以也不排除显示器本身的问题，因为之前发现，同一款电脑，使用 LG 的屏幕就不会出现问题，而奇美的就会

**Comment by bingcheng1998** [comment]
发现了，截图是连续的。应该是显示器有些问题。但是不应该的，我不开HiHPI就不会有条纹。所以应该不是显示器的问题。应该是显卡设置的问题，导致截图没问题但是显示有条纹。应该可以用修改配置解决。

**Comment by xzhih** [comment]
结合上面我说的仿冒 hd520 可以解决，这样看就是显卡驱动的问题。
10.13 的时候就发现这个问题了，10.13.6 的时候似乎已经解决，但是 10.14 问题又复现了。
难搞啊

**Comment by bingcheng1998** [comment]
![image](https://user-images.githubusercontent.com/26592478/63673770-9d472800-c817-11e9-86c1-101947bdf5a3.png)
我就是13.3.6，没有升级，但是任然有这个问题。
