### ISSUE TITLE
如果需要经常旋转显示器怎么办。。比如我。。

### ISSUE THREAD

**Issue by leafleave** [xzhih/one-key-hidpi#68]
如果需要经常旋转显示器怎么办。。比如我。。

_Originally posted by @leafleave in https://github.com/xzhih/one-key-hidpi/issues/43#issuecomment-524502171_

**Comment by xzhih** [comment]
旋转后可以在设置里选择缩放分辨率的啊，也是 hidpi 的

**Comment by oldzhg** [comment]
> 旋转后可以在设置里选择缩放分辨率的啊，也是 hidpi 的

横屏情况下在设置里面内建显示器分辨率有之前添加的1600x900等等 但是旋转内建显示器90度后 缩放分辨率只有1080x1920 再次执行脚本手动添加 900x1600 重启后还是只有一个1080x1920 这种情况能解决吗？
附内建显示器开启旋转选项 http://www.welwifi.com/?id=556
