### ISSUE TITLE
你好,可以提供一个选项仅修改图标不使用hidpi吗

### ISSUE THREAD

**Issue by fanvinga** [xzhih/one-key-hidpi#7]
如题,不知如何修改使hidpi关闭但偏好设置中图标保留?
看了下脚本的内容,Info.plist中引用了图标的路径为生成的DisplayVendorID文件夹内部的内容,不确定仅改变路径是否正常生效

**Comment by xzhih** [comment]
不想使用HIDPI的话，运行脚本后，删除 DisplayVendorID 配置中 scale-resolutions 部分的内容就行了

**Comment by fanvinga** [comment]
DisplayVendorID 有很多个文件夹,都删除吗?

**Comment by xzhih** [comment]
运行脚本后，进入到生成的DisplayVendorID文件夹，里面有个配置文件，删除 scale-resolutions 下的分辨率设置

**Comment by fanvinga** [comment]
感谢帮助,修改成功了:-D
