### ISSUE TITLE
dell 燃7000 外接2k显示器，无法开启HIDPI。

### ISSUE THREAD

**Issue by bitxinyu** [xzhih/one-key-hidpi#70]
老哥，电脑是老版本的dell燃7000，7460，外接了AOC2k显示器，分辨率2560x1440，想开成1920x1080，但是没有效果。

**Comment by xzhih** [comment]
有些显示器获取不到正确的 VendorID 和 ProductID，这我就没办法了

**Comment by bitxinyu** [comment]
> 有些显示器获取不到正确的 VendorID 和 ProductID，这我就没办法了

应该获取到正确的VendorID和ProductID了， 我选择不同的分辨率配置，RDM里的选项是不一样的

**Comment by xzhih** [comment]
试试这个命令
```bash
sudo defaults write /Library/Preferences/com.apple.windowserver DisplayResolutionEnabled -bool YES
```

如果还调不了，就去试试其他的开启方法，用 FixEDID 之类的

**Comment by bitxinyu** [comment]
> 试试这个命令
> 
> ```shell
> sudo defaults write /Library/Preferences/com.apple.windowserver DisplayResolutionEnabled -bool YES
> ```
> 
> 如果还调不了，就去试试其他的开启方法，用 FixEDID 之类的

还是不行，哭了，试试其他分辨率，2560x1440后面都能出来闪电，偏偏1920x1080出不来。。。

**Comment by cclover** [comment]
我也是没有1920*1080的 hidpi，显示器 HP E273Q

**Comment by bitxinyu** [comment]
> 我也是没有1920*1080的 hidpi，显示器 HP E273Q

我还用了DarwinDumper和FixEDID，还是不行，目前已放弃 :(

**Comment by cclover** [comment]
我用DarwinDumper和FixEDID，已经OK了。就是的用RDM，不能直接从系统设置里改。

**Comment by bitxinyu** [comment]
> 我用DarwinDumper和FixEDID，已经OK了。就是的用RDM，不能直接从系统设置里改。

好奇怪，我这fixedid计算和生成的vendorID和productID不一致。。
![微信图片_20190927232224](https://user-images.githubusercontent.com/11964010/65781399-27b7da00-e17e-11e9-960a-ba800348887f.jpg)

**Comment by xzhih** [comment]
FixEDID 用的是Mac的信息，脚本用的是显示器的
