### ISSUE TITLE
BenQ EW277HDR 無法開啟 HiDPI

### ISSUE THREAD

**Issue by tronic1983** [xzhih/one-key-hidpi#71]
腳本執行成功，EDID 修正也成功注入，就是沒有辦法開啟 HiDPI。

螢幕： BenQ EW277HDR
連接線： Mini DP to HDMI
電腦： 13 吋 Macbook Pro Retina 2013 Late
macOS：Mojave

非常感謝。

**Comment by xzhih** [comment]
执行这个命令

```bash
sudo defaults write /Library/Preferences/com.apple.windowserver DisplayResolutionEnabled -bool YES
```

**Comment by tronic1983** [comment]
感謝如此迅速的回覆。

我已經執行過了那個命令，可惜還是失敗了！

選擇縮放，仍然沒有辦法如同原生的 HiDPI 選項。

目前推測應該是 EDID 沒有完全成功套用。

因為，EDID 成功套用後，在系統報告 -> 顯示 那個欄位，會看到 "EW277HDR - force RGB mode (EDID override)" 這行字樣，可是並沒有出現。

然而，色彩顯示是正確的，並沒有強制為 HD-709A 的顏色輸出。

可否請您再做些測試工作呢？

**Comment by xzhih** [comment]
你使用 [RDM](http://avi.alkalay.net/software/RDM/RDM-2.2.pkg) 是否能看到 hidpi 分辨率的开启选项？

脚本里的 EDID 是没有开启  force RGB mode 的，所以关于 EDID 注入的判断可能不对。

Macbook 是需要将 SIP 关闭才能写入系统分区的，你应该看一下 `/System/Library/Displays/Contents/Resources/Overrides` 这个目录下是否成功生成了你显示器对应的配置文件

**Comment by tronic1983** [comment]
感謝您迅速的回覆。

原來腳本裡的 EDID 沒有開啟 force RGB mode 啊！原來如此。

我已經將 SIP 關閉，系統分區的目錄下有生成顯示器對應的配置文件，只有 RDM 看不到閃電標誌，很是奇怪。

**Comment by xzhih** [comment]
你可能需要尝试一下使用 `darwin dumper` 和 `fixEDID` 这两个工具来开启 HIDPI，相关教程应该能搜索到，找不到可以再回复

**Comment by tronic1983** [comment]
好的！感謝！我先自己嘗試看看，真的需要您的協助，我再來回覆。

**Comment by tronic1983** [comment]
> 你可能需要尝试一下使用 `darwin dumper` 和 `fixEDID` 这两个工具来开启 HIDPI，相关教程应该能搜索到，找不到可以再回复

感謝您的建議，成功了！我先用您的 script 注入 EDID 之後，再按照您的說明來做，就可以開啟 HiDPI。

雖然跟您在 Github 的說明不太相同，但是可以用，也確保了色準。

此外，在這邊有個小小建議，由於 macOS 先天的限制，使用外接螢幕的時候，很容易把外接螢幕辨認為 HDTV。

因此，可以考慮在 script 中加入 force RGB mode (EDID override)，讓 macOS 強制使用 RGB 輸出信號，以免色彩變得很奇怪，也可以加強字體渲染的平滑度。

最後，再次感謝您的幫忙與回應，雖然繞了一大圈，但是解決了問題，真的很開心。

**Comment by xzhih** [comment]
那我有时间把 force RGB mode (EDID override) 作为一个可选项

**Comment by tronic1983** [comment]
如此真的是太棒啦！感激不盡！若有更新這項功能也請通知我一聲，太感謝了。

**Comment by cclover** [comment]
我也是，默认没有1080的HIDPI，自己重新弄了EDID开启了。不过只能用RDM设置，设置界面还不是系统那样的。 请问这个能修改好吗？
