### ISSUE TITLE
关于DELL U2515H 开启hidpi的问题

### ISSUE THREAD

**Issue by hwanginpen** [xzhih/one-key-hidpi#72]
您好，
我目前使用的是
MacBook Pro (13-inch, 2019)
显示器：DELL U2515H (2K分辨率)
盒盖外接显示器使用。

现在的疑惑是：如果想用这个2k分辨率显示器开启hidpi，执行了您提供的命令，在那个“选择要显示的icon” 和 “选择分辨率配置” 分别要选择哪个呢？这里有点不懂，不敢乱选。

另外，如果用过您提供的已经执行过一次命令选择了2k显示屏，想要用您的命令改回1080p显示屏，是否可以执行命令直接修改呢，需不需要先恢复然后再修改？

谢谢！

**Comment by xzhih** [comment]
icon选你喜欢的都行，这个没啥影响，比如我选择了 `pro display xdr`，然后分辨率选择你屏幕的物理分辨率，2515是2k的就选2k

如果你要改回去，再执行一次命令后选择 **关闭 HIDPI**

2k的的显示器，什么叫改回 1080p？

**Comment by hwanginpen** [comment]
好的我明白了！ 
“2k的的显示器，什么叫改回 1080p？” ：这个没事了，我搞懂了。

执行命了，选择了lg显示器和2k分辨率成功开启hidpi。偏好设置-显示器 那里没得选1920x1080，只有2048x1152。但是通过RDM可以选择1920x1080，屏幕很清晰，完美！

<img width="665" alt="屏幕快照 2019-09-10 下午1 02 35" src="https://user-images.githubusercontent.com/38434400/64580859-46228500-d3cb-11e9-92c6-5892900c2c62.png">

<img width="339" alt="屏幕快照 2019-09-10 下午1 04 39" src="https://user-images.githubusercontent.com/38434400/64580953-a285a480-d3cb-11e9-8aef-98610964a348.png">

**Comment by bsdcpp** [comment]
我也是U2515H，直接用2048x1152就行了，比1080课时范围更大，也是hidpi的

**Comment by HoldenWang** [comment]
我u2717d，尝试失败，重启没有什么变化。
