### ISSUE TITLE
关于10.15权限问题和解决方法

### ISSUE THREAD

**Issue by haoboxuxu** [xzhih/one-key-hidpi#75]
catalian在display没有权限，我的解决方法是把旧的文件sudo su cp会去，重启可以解决

**Comment by hadix-lin** [comment]
怎么解决的，能详细点儿说明吗？

**Comment by haoboxuxu** [comment]
我是在10.14有开启hidpi了，升级10.15后桌面有个叫迁移项目的文件夹，里面是被系统安全踢出的hidpi文件，在终端使用sudo su cp -R命令把迁移项目的文件夹拷贝到路径：/系统/资源库/Displays/Contents/Resources/Overrides/，就可以恢复

**Comment by lhy920816** [comment]
> 我是在10.14有开启hidpi了，升级10.15后桌面有个叫迁移项目的文件夹，里面是被系统安全踢出的hidpi文件，在终端使用sudo su cp -R命令把迁移项目的文件夹拷贝到路径：/系统/资源库/Displays/Contents/Resources/Overrides/，就可以恢复

您能再详细说下怎么操作吗？  sudo命令不会用。。。编程小白

**Comment by fengbeibei** [comment]
> > 我是在10.14有开启hidpi了，升级10.15后桌面有个叫迁移项目的文件夹，里面是被系统安全踢出的hidpi文件，在终端使用sudo su cp -R命令把迁移项目的文件夹拷贝到路径：/系统/资源库/Displays/Contents/Resources/Overrides/，就可以恢复
> 
> 您能再详细说下怎么操作吗？ sudo命令不会用。。。编程小白

sudo cp -R {桌面上的overrides文件夹路径}  {系统的overrides文件夹路径}

我的是：
sudo cp -R /Users/Shared/Relocated\ Items/Security/System/Library/Displays/Contents/Resources/Overrides /System/Library/Displays/Contents/Resources/Overrides

**Comment by hadix-lin** [comment]
10.15 的系统文件目录是只读挂载的，所以做执行sudo cp -R .... 命令之前，还要把系统目录挂载为读写模式。

需要先执行`sudo mount -uw /`

**Comment by xzhih** [comment]
脚本早就支持 10.15 了，为什么还要折腾，搞不懂你们

**Comment by haoboxuxu** [comment]
> 10.15 的系统文件目录是只读挂载的，所以做执行sudo cp -R .... 命令之前，还要把系统目录挂载为读写模式。
> 
> 需要先执行`sudo mount -uw /`

好的，谢谢
