### ISSUE TITLE
关于macos 10.15 版本1080p hidpi无法启用

### ISSUE THREAD

**Issue by guomk** [xzhih/one-key-hidpi#76]
10.15 Beta (19A582a)（GM版）无法启用1080p hidpi

**Comment by xieyx** [comment]
我的显示器是Dell U2518D, 2K分辨率, 也是无法开启1080p hidpi, 开启2k就可以了, 可以试试

**Comment by Jamesxxx1997** [comment]
> 我的显示器是Dell U2518D, 2K分辨率, 也是无法开启1080p hidpi, 开启2k就可以了, 可以试试
請問是什麼意思？ 2K分辨率的屏幕在選項中不是就是要選2K解析度的選項嗎？ 謝謝

**Comment by xzhih** [comment]
![image](https://user-images.githubusercontent.com/13920737/67157561-4580f500-f360-11e9-90cf-37ed9df80340.png)

我可以

**Comment by mmkkllpp** [comment]
我2k的显示器，也是无法开1080了，只有1680*944，之前10.15之前可以，升级了10.15.1就不行
