### ISSUE TITLE
10.15 catalina 正常工作 但运行缓慢

### ISSUE THREAD

**Issue by IvyB** [xzhih/one-key-hidpi#77]
首先要进recovery关闭csr，重启调好hidpi后再进recovery开启csr

关闭CSR命令：
```
csrutil disable
```

<img width="1440" alt="截屏2019-10-0812 51 34" src="https://user-images.githubusercontent.com/7955928/66369184-f507b000-e9cd-11e9-860f-fb07231b7e91.png">

型号和分辨率均注入成功

但脚本运行时 选型号和选分辨率运行缓慢，需要等待数分钟

**Comment by pincheung** [comment]
重启后还是要我关闭sip，这是我在recovery少了哪个步骤吗？

**Comment by IvyB** [comment]
> 重启后还是要我关闭sip，这是我在recovery少了哪个步骤吗？

我的recovery模式下，敲一行命令重启就可以了。也许你需要试试sudo运行hidpi.sh
