### ISSUE TITLE
10.15正式版开启失败

### ISSUE THREAD

**Issue by timighg** [xzhih/one-key-hidpi#78]
每次重启完就会恢复 怎么解决？

**Comment by cuiziwei** [comment]
那就别重启哈哈

**Comment by timighg** [comment]
> 那就别重启哈哈

重启生效...没重启也没生效啊

**Comment by cuiziwei** [comment]
别人说得先把 csrutil disable 禁用掉再用这个脚本，要不然没权限可以试试

**Comment by cuiziwei** [comment]
看下这个 https://github.com/xzhih/one-key-hidpi/issues/57

**Comment by shiny** [comment]
我用的是正式版，没遇到这个问题。难道是因为关了 SIP
