### ISSUE TITLE
sipChecker parse error

### ISSUE THREAD

**Issue by maddie** [xzhih/one-key-hidpi#79]
OS: 10.15 Catalina
Hackintosh with OpenCore bootloader, `csr-active-config` set to `E7030000`.

`csrutil status` output as below:

```
System Integrity Protection status: unknown (Custom Configuration).

Configuration:
	Apple Internal: disabled
	Kext Signing: disabled
	Filesystem Protections: disabled
	Debugging Restrictions: disabled
	DTrace Restrictions: disabled
	NVRAM Protections: disabled
	BaseSystem Verification: disabled

This is an unsupported configuration, likely to break in the future and leave your machine in an unknown state.
```

`csrutil status | awk '{ print $5 }` output as below:

```
unknown










configuration,
```

SIP is actually disabled in this configuration, but the script only checks if the output equals to `disabled.`

**Comment by xzhih** [comment]
Disable SIP in Recovery OS, no need set `csr-active-config`.

```bash
csrutil disable
```

**Comment by maddie** [comment]
Thanks for your reply. Using `csrutil` on my machine somehow doesn't seem to have the config stick in NVRAM.

I've disabled the check in the script for now, as this is not the standard way to disable SIP, so I assume it won't be supported.

Closing issue. Thanks again!

**Comment by xzhih** [comment]
In addition, on devices that do not support native nvram, you can set `csr-active-config` to 67000000.

**Comment by maddie** [comment]
It would be nice to have this info in README or Wiki for those who might encounter the same problem/with the same setting :)

**Comment by xseman** [comment]
Setting `csr-active-config` to `67000000` doesn't work, deleting `csr-active-config` and manually disabling `csrutil disable` in recovery doesn't work, too
