### ISSUE TITLE
10.15 正式版内置显示器开启成功，但是外接显示器开启不成功

### ISSUE THREAD

**Issue by vimcaw** [xzhih/one-key-hidpi#80]
以前在 10.14 的时候外接显示器也是正常的。

![image](https://user-images.githubusercontent.com/21964227/66618526-f0c8d600-ec0b-11e9-9d99-0596e2707ffd.png)

开启后重启，还是原来的：

![image](https://user-images.githubusercontent.com/21964227/66618478-caa33600-ec0b-11e9-811e-265e8e1347fd.png)

**Comment by xzhih** [comment]
应该跟核显驱动更新了有关，这我无法解决，脚本只是虚拟了这些假的分辨率配置，并没有改变其他的任何东西。

**Comment by vimcaw** [comment]
@xzhih 感谢回复，但奇怪的是内置的显示器确可以正常开启，这两个显示器是共用同一个核显的。

![image](https://user-images.githubusercontent.com/21964227/66621216-e57aa800-ec15-11e9-8748-8088d912f8c6.png)

**Comment by xzhih** [comment]
内置和外接是不同

**Comment by vimcaw** [comment]
ok，我去看看其他原因

**Comment by vimcaw** [comment]
用此脚本处理完再配合 [RDM](https://github.com/avibrazil/RDM) 软件，选择带闪电的分辨率后，成功开启 HiDPI。

![image](https://user-images.githubusercontent.com/21964227/66972185-69c1a500-f0c6-11e9-8815-aef2e22d904b.png)
