### ISSUE TITLE
1080 分辨率显示器 可以开启1920分辨率这个hidpi吗？

### ISSUE THREAD

**Issue by xuechao2008** [xzhih/one-key-hidpi#83]
mojave 10.14.6
显示器 dell u2312hm 和 dell u2414h 
最大分辨率1920  x 1080

现在开启后 最大只能选择 
1680 x 944 （hidpi）这个
还有一个
1280 x 720   （hidpi）
1920的没有hidpi 标识

开启后没有出现图标选择的样子， 就是一列分辨率选择 ，这样是开启了吗？
我看开启后最大分辨率是3360 x 1888  是我这个显示器的问题吗？ 正常应该是
3840 x 2160 才是1920 hidpi 开启的

里面说重启logo变大 ，我这个直接就变小很多 ，貌似直接改成了最大分辨率 3360 x 1888

请问我这个显示器是不能开启1920 的hidpi吗？

**Comment by xzhih** [comment]
你要先搞懂 `HIDPI` 是什么，它使用横纵 2 个物理像素也就是 4 个物理像素来显示 1 个像素区域，结果就是图像的细节得到翻倍、更清晰、边缘更平滑。

拿 13 寸的 MacBook Pro 举例，它的屏幕物理分辨率是 2560 x 1600，所以原生的 `HIDPI` 分辨率就是 1280x800。更高的一档 1440x900 hidpi 缩放分辨率，则是虚拟出一个 2880x1800 的分辨率，再进行软缩放输入。所以你能发现苹果的电脑总是有很高的分辨率。

好了，既然你的屏幕是 `1080p`，本身就没有那么多像素去合成  `HIDPI`，如果以原生的显示计算，你这屏幕的 `1080p` 分辨率应该是 960x540，这么低的分辨率你是没法用的，所以就有了这个脚本。

这个脚本的功能是虚拟出比你的屏幕物理分辨率更高的假分辨率，也就是你看到的 3360 x 1888，这样你就可以使用 1680 x 944 hidpi 这个缩放分辨率了。

如果你要开启 1080p 的 HIDPI 分辨率，就虚拟一个 3840 x 2160 的假分辨率，然后 MacOS 会使用 4 个像素来显示 1 个像素区域，也就是和你物理分辨率一样的 1080p 分辨率，开不开启看起来没任何区别，最大的效果就是显卡压力增大系统变卡、截图可以得到高分辨率图像。

所以说，试图开启和物理分辨率一样的 HIDPI 分辨率，是愚蠢的行为。

因为有很多人问过这个问题，所以我详细的回复一下。

**Comment by xuechao2008** [comment]
> 你要先搞懂 `HIDPI` 是什么，它使用横纵 2 个物理像素也就是 4 个物理像素来显示 1 个像素区域，结果就是图像的细节得到翻倍、更清晰、边缘更平滑。
> 
> 拿 13 寸的 MacBook Pro 举例，它的屏幕物理分辨率是 2560 x 1600，所以原生的 `HIDPI` 分辨率就是 1280x800。更高的一档 1440x900 hidpi 缩放分辨率，则是虚拟出一个 2880x1800 的分辨率，再进行软缩放输入。所以你能发现苹果的电脑总是有很高的分辨率。
> 
> 好了，既然你的屏幕是 `1080p`，本身就没有那么多像素去合成 `HIDPI`，如果以原生的显示计算，你这屏幕的 `1080p` 分辨率应该是 960x540，这么低的分辨率你是没法用的，所以就有了这个脚本。
> 
> 这个脚本的功能是虚拟出比你的屏幕物理分辨率更高的假分辨率，也就是你看到的 3360 x 1888，这样你就可以使用 1680 x 944 hidpi 这个缩放分辨率了。
> 
> 如果你要开启 1080p 的 HIDPI 分辨率，就虚拟一个 3840 x 2160 的假分辨率，然后 MacOS 会使用 4 个像素来显示 1 个像素区域，也就是和你物理分辨率一样的 1080p 分辨率，开不开启看起来没任何区别，最大的效果就是显卡压力增大系统变卡、截图可以得到高分辨率图像。
> 
> 所以说，试图开启和物理分辨率一样的 HIDPI 分辨率，是愚蠢的行为。
> 
> 因为有很多人问过这个问题，所以我详细的回复一下。

万分感谢耐心解答！了解了！

**Comment by chengjianhao** [comment]
但是24寸1080 的显示屏用mac系统，字体效果真是太差了，有什么改善的方法吗。

**Comment by troicc** [comment]
> 如果你要开启 1080p 的 HIDPI 分辨率，就虚拟一个 3840 x 2160 的假分辨率，然后 MacOS 会使用 4 个像素来显示 1 个像素区域，也就是和你物理分辨率一样的 1080p 分辨率，开不开启看起来没任何区别，最大的效果就是显卡压力增大系统变卡、截图可以得到高分辨率图像
HiDPI可以形象的认为是先放大再缩小，在相同面积上由3840 2160到1920 1080和直接使用物理1920 1080效果自然不一样，而前者能够提高观感也正是HiDPI的作用所在。你所谓没任何区别不是胡诌吗。最直观的从截图文件大小上看就知道。。。
