### ISSUE TITLE
hidpi開啟異常

### ISSUE THREAD

**Issue by Jamesxxx1997** [xzhih/one-key-hidpi#84]
您好，我的筆記本thinkpad x1 yoga 2018 , 2K的分辨率

屏幕原本的vendor id與product id分別是2889和0

發現了兩個問題
1. 如果開啟hidpi

- 筆記本螢幕的hidpi最高只有1440x810 , 而且icon跟原來的相同

2. 如果先用hackintool在config.plistr中注入AAPL00,override-no-connect

- 筆記本螢幕的hidpi最高只有1440x810 ,不過可以更換icon了

- icon如果選擇macbook,macbook pro,iMac,，顯示出來的圖標都是LG display
-icon如果選擇Pro Display XDR , 顯示出來的圖標就是Pro Display XDR

上傳了我的debug file , 不知道您有空是否能幫忙看看，感謝～
[28525.zip](https://github.com/xzhih/one-key-hidpi/files/3747144/28525.zip)

註：
1. 使用您的腳本、fixEDID+darwindumper、hackintool , 均無法開啟大於1440x810的分辨率
2. 這個問題是在更新系統(10.14.4 -> 10.14.6)後出現的
3. 外接[1080P顯示器](https://www.viewsonic.com/tw/products/lcd/VX2476-smhd.php)在您的腳本下，是能正常開啟hidpi的(最高2048x1152)，

**Comment by xzhih** [comment]
我覺得你的筆記本熒幕 EDID 不規範，或者是 MacOS 沒法正確獲取，`AAPL00,override-no-connect` 是用來注入 EDID 的，但是本身獲取到的也是有問題的 EDID，所以你最好在 Windows 下獲取到 EDID 后，填入到 `AAPL00,override-no-connect` 里，但是腳本可能還是沒法生效，你需要一切都是手動設置。

`無法開啟大於1440x810的分辨率` 應該是系統的限制，這個我沒有解決辦法

**Comment by Jamesxxx1997** [comment]
感謝您的回覆，您的意思是
1. 先在windows下獲取EDID，注入到AAPL00,override-no-connect
2. 在macos下手動使用fixEDID+darwindumper加上方便率嗎？


>>>無法開啟大於1440x810的分辨率 應該是系統的限制，這個我沒有解決辦法
請問您是指10.14.6下作業系統的限制嗎？


因為我原本在10.14.4之下是能正常使用1920*1080的hidpi的

我沒有關掉hidpi就直接更新到10.14.6了;更新完後不僅icon從原本的macbookpro變成iMac , 1920*1080的hidpi也失效了
所以想跟您確認一下，hidpi在更新之前是要先關閉的嗎？ 謝謝您～

**Comment by xzhih** [comment]
你可以試試 windows 下獲取 EDID 並注入，不過我也不知道會不會讓腳本或 darwindumper 獲取得到正確的 EDID，畢竟都是從 ioreg 裏拿到的。你需要自己多嘗試，我這些都只是推測。

MacOS 更新后腳本開啟的 hidpi 會自動失效，需要重新使用腳本之類。

MacOS 更新后顯卡驅動和一些配置會更改，這可能會導致無法對內置熒幕開啟大於 1440p 的 hidpi。

**Comment by Jamesxxx1997** [comment]
感謝您的提點～
在win下提取edid後，在clover注入edid就能夠不經由AAPL00,override-no-connect來開啟hidpi了
<img width="983" alt="image" src="https://user-images.githubusercontent.com/29252582/67160917-2302d200-f388-11e9-86f7-9a261e3185a7.png">
不過也是只能最高開啟到1440*810的hidpi

>>>MacOS 更新后顯卡驅動和一些配置會更改，這可能會導致無法對內置熒幕開啟大於 1440p 的 hidpi
請問您這段話的意思指的是，更新後新版本的系統原本就對於2K的屏幕不支持1920*1080的hidpi嗎？ 還是更新了新系統後影響了系統內的某些參數，導致無法開啟更高的hidpi呢？
如果是您的意思是指後者的話，代表需要重灌mac系統嗎？ 還是把原本備份好的S\L\E替換回去就好了呢？

再次感謝！！！

**Comment by xzhih** [comment]
應該是顯卡驅動對內置熒幕的最大輸出限制，你可以試試設置到 4k 的 hidpi 數據。

我建議不要把舊版本的驅動替換到新版本系統

**Comment by Jamesxxx1997** [comment]
>應該是顯卡驅動對內置熒幕的最大輸出限制，你可以試試設置到 4k 的 hidpi 數據。

好的～ 我之後再做測試，也分割一個磁碟區重裝系統試試看
不過我之前因為電腦浸水回原廠換過同樣的2K螢幕，不知道跟這個問題有沒有關係

>我建議不要把舊版本的驅動替換到新版本系統

😂😂更新系統時都把驅動和clover更新到最新了～

**Comment by xzhih** [comment]
> 😂😂更新系統時都把驅動和clover更新到最新了～

我的意思是不要對系統目錄裏的驅動操作，clover 裏的升級沒事

**Comment by Kyleinhurricane** [comment]
我之前测试过是在某些特定的显卡id下会有分辨率的限制，建议你更换注入的显卡id

**Comment by Jamesxxx1997** [comment]
> 我之前测试过是在某些特定的显卡id下会有分辨率的限制，建议你更换注入的显卡id

我的iGPU是uhd620 , 應該就是59160000了（？

**Comment by xzhih** [comment]
@Jamesxxx1997 注入5916，启动参数加个 `lilucpu=9`

**Comment by Kyleinhurricane** [comment]
> > 我之前测试过是在某些特定的显卡id下会有分辨率的限制，建议你更换注入的显卡id
> 
> 我的iGPU是uhd620 , 應該就是59160000了（？

同一个显卡可以仿冒不同的id的

**Comment by Jamesxxx1997** [comment]
> 同一个显卡可以仿冒不同的id的

筆記本上，uhd 620應該都是用59160000的 :(

**Comment by vimcaw** [comment]
如果 macOS 版本高于 10.13.6，要开启更高 HiDPI 分辨率 (\<1520x855)，要修改 DVMT 来把动态显存设为 64MB。
