### ISSUE TITLE
不知道能不有在带鱼屏幕上开启，我刚试了一下，在终端上读取不到代码！

### ISSUE THREAD

**Issue by SimonLuoshiping** [xzhih/one-key-hidpi#87]
不知道能不有在带鱼屏幕上开启，我刚试了一下，在终端上读取不到代码！

**Comment by xzhih** [comment]
远景上有21:9成功的案例

不知道你说的读取不到代码是什么意思，什么代码？

**Comment by SimonLuoshiping** [comment]
就是我终端上输入了没有反应

**Comment by SimonLuoshiping** [comment]
出现curl: (7) Failed to connect to raw.githubusercontent.com port 443: Operation timed out

**Comment by xzhih** [comment]
那是你那里的 `raw.githubusercontent.com` 被墙了，跟脚本没有任何关系

**Comment by SimonLuoshiping** [comment]
我没有墙吧，我是一直全局vpn的。也可以在浏览器也可以直接访问

**Comment by xzhih** [comment]
#88 
复制终端代理命令到终端粘贴回车，让终端挂上代理
如果不行，那也是你的网络问题
