### ISSUE TITLE
Surface Pro 4 运行脚本后没有缩放选项

### ISSUE THREAD

**Issue by damaoooo** [xzhih/one-key-hidpi#90]
如题，surface pro 4 能够完美运行脚本并重启
开启之后仍然是只有一个分辨率的那个原始缩放界面，并没有成功之后的效果

**Comment by xzhih** [comment]
选手动，注入4k的分辨率

**Comment by damaoooo** [comment]
> 选手动，注入4k的分辨率

系统版本是10.15，surface原生分辨率是2736x1824
重新运行脚本后手动注入4K分辨率3840x2160后重启，在BIOS界面死机，再次重启，进入界面发现依旧
![IMG_20191112_163457](https://user-images.githubusercontent.com/45312642/68655153-7375e580-056a-11ea-82dc-b17433b463f6.jpg)
打开RDM发现有1368x912的带有闪电符号的分辨率，点击之后毫无反应

**Comment by Chillimeat** [comment]
> > 选手动，注入4k的分辨率
> 
> 系统版本是10.15，surface原生分辨率是2736x1824
> 重新运行脚本后手动注入4K分辨率3840x2160后重启，在BIOS界面死机，再次重启，进入界面发现依旧
> ![IMG_20191112_163457](https://user-images.githubusercontent.com/45312642/68655153-7375e580-056a-11ea-82dc-b17433b463f6.jpg)
> 之前试过注入原生分辨率，2K，4K，和上图一样
> 打开RDM发现有1368x912的带有闪电符号的分辨率，点击之后毫无反应

我的问题跟你一样，只是我的是XPS15 外接21:9的显示器。

**Comment by kaikai0706** [comment]
我也是这样，没有缩放！
