### ISSUE TITLE
how to uninstall ?

### ISSUE THREAD

**Issue by thomasdba** [xzhih/one-key-hidpi#92]
我以前是用老显示器，现在用新的4K显示器，应该用不到了吧，而且我发现现在显示里，没有办法调节亮度，根本就没有这选项，也不显示刷新率，虽然是10.15，但还是像上一代似的显示。

**Comment by xzhih** [comment]
第一，脚本根据显示器注入，所以新显示器不可能会用到旧显示器的数据

第二，脚本第三个选项就是卸载

第三，你 4k 没显示 hidpi 应该是显卡驱动问题，去搜一下解决吧，我看到不少人遇到了

**Comment by thomasdba** [comment]
scaled这是可以调节的，这应该是hidpi了吧，只是下面没有亮度和刷新率调节 ，有点奇怪，谢谢

**Comment by xzhih** [comment]
外置显示器除非是 apple 的，不然没法原生调节亮度的吧，你可以用 MonitorControl 这个软件调节

刷新率可以用 RDM 调

**Comment by thomasdba** [comment]
提了一个不相关的问题，还得到了解答，非常感谢！
