### ISSUE TITLE
10.15.1 脚本无效

### ISSUE THREAD

**Issue by gorda** [xzhih/one-key-hidpi#93]
先给作者大佬点个赞👍，帮助了我们这些垃圾佬。

我的情况是刚刚装上黑果，直接装的 10.15.1，想开启 hiDPI，似乎脚本失效了。

我已经参考 [10.15 权限问题](https://github.com/xzhih/one-key-hidpi/issues/57)
- 根目录 `/` 已经可以读写
- 用 ps aux 查看 pid，确定了 Finder 的 pid 已经变化
- 脚本选择是 2-6-3
- 脚本运行没有报错
- 重启电脑 hiDPI 没有开启，但是出现了闪屏问题
- 显卡是 RX570

**Comment by xzhih** [comment]
脚本有没有失效，取看看 `/System/Library/Displays/Contents/Resources/Overrides` 里有没有你显示器对应的配置文件了。

有，但是没开启，就是其他原因。

脚本只是生成了配置文件，让系统读取罢了，没做其他修改，因为MacOS内只有apple自己家及合作生产的显示器有配置文件。

**Comment by gorda** [comment]
我在 11:38 重新执行脚本后，你说的目录下多了一个目录

> drwxr-xr-x    3 root  wheel    96B 11 17 11:38 DisplayVendorID-2163

目录下有一个名为 `isplayProductID-00` 的文件，内容是：
```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
    <dict>
        <key>DisplayProductID</key>
            <integer>0</integer>
        <key>DisplayVendorID</key>
            <integer>8547</integer>
        <key>IODisplayEDID</key>
            <data>AP///////wAhYwAAAAAAAAoYAQSQPCJ44j2FplZKmiQSUFSvzwDRwLMAlQCBgIHAgQABAQEBVl4AoKCgKVAwIDUAVVAhAAAaAAAA/ABIRE1JCiAgICAgICAgAAAA/QA3Sw9jGQAKICAgICAgAAAA/wAwMDAwMDAwMDAwMDAxAZo=</data>
        <key>scale-resolutions</key>
            <array>
                <data>AAAQAAAACQAA</data>
                <data>AAAPAAAACHAA</data>
                <data>AAANIAAAB2AA</data>
                <data>AAALQAAABlQA</data>
                <data>AAAKAAAABaAA</data>
                <data>AAAIAAAABIAAAAABACAAAA==</data>
                <data>AAAHgAAABDgAAAAB</data>
                <data>AAAQAAAACQAAAAAJAKAAAA==</data>
                <data>AAAPAAAACHAAAAAJAKAAAA==</data>
                <data>AAAKAAAABkAAAAABACAAAA==</data>
                <data>AAAKAAAABaAAAAABACAAAA==</data>
                <data>AAAHgAAABLAAAAABACAAAA==</data>
                <data>AAAHgAAABDgAAAABACAAAA==</data>
                <data>AAAFAAAAAtAAAAABACAAAA==</data>
                <data>AAAGkAAAA7AAAAAB</data>
                <data>AAAGQAAAA4QAAAAB</data>
                <data>AAAFoAAAAyoAAAAB</data>
                <data>AAAFAAAAAtAAAAAB</data>
                <data>AAAEgAAAAogAAAAB</data>
                <data>AAAEAAAAAkAAAAAB</data>
                <data>AAADSAAAAdQAAAAB</data>
                <data>AAADIAAAAcIAAAAB</data>
                <data>AAACgAAAAWgAAAAB</data>
                <data>AAANIAAAB2AAAAAJAKAAAA==</data>
                <data>AAALQAAABlQAAAAJAKAAAA==</data>
                <data>AAAKAAAABaAAAAAJAKAAAA==</data>
                <data>AAAIAAAABIAAAAAJAKAAAA==</data>
                <data>AAAHgAAABDgAAAAJAKAAAA==</data>
                <data>AAAGkAAAA7AAAAAJAKAAAA==</data>
                <data>AAAGQAAAA4QAAAAJAKAAAA==</data>
                <data>AAAFAAAAAtAAAAAJAKAAAA==</data>
            </array>
        <key>target-default-ppmm</key>
            <real>10.0699301</real>
    </dict>
</plist>
```
看起来确实生成了配置文件，就是不知道为啥系统没有读取……

**Comment by gorda** [comment]
作者大人，我参考另外一篇 [文章](https://heipingguowu.top/2019/10/08/2319/) 使用了 hackintool 方法，成功开启了 hiDPI（虽然效果不怎么理想……）。
其生成的配置文件如下：
```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>DisplayProductID</key>
	<integer>0</integer>
	<key>DisplayVendorID</key>
	<integer>8547</integer>
	<key>IODisplayEDID</key>
	<data>
	AP///////wAGEHycAAAAAAoYAQSAPCJg4m+xp1VMniUMUFSvzwDRwLMAlQCBgIHAgQAB
	AQEBVl4AoKCgKVAwIDUAVVAhAAAaAAAA/ABIRE1JCiAgICAgICAgAAAA/QA3Sw9jGQAK
	ICAgICAgAAAA/wAwMDAwMDAwMDAwMDAxAbk=
	</data>
	<key>scale-resolutions</key>
	<array>
		<data>
		AAAQAAAACQAA
		</data>
		<data>
		AAAPAAAACHAA
		</data>
		<data>
		AAANIAAAB2IA
		</data>
		<data>
		AAALQAAABlQA
		</data>
		<data>
		AAAKAAAABaAA
		</data>
		<data>
		AAAIAAAABIAAAAABACAAAA==
		</data>
		<data>
		AAAHgAAABDgAAAAB
		</data>
		<data>
		AAAQAAAACQAAAAAJAKAAAA==
		</data>
		<data>
		AAAKAAAABaAAAAABACAAAA==
		</data>
		<data>
		AAAHgAAABDgAAAABACAAAA==
		</data>
		<data>
		AAAFAAAAAtAAAAABACAAAA==
		</data>
		<data>
		AAAGkAAAA7AAAAAB
		</data>
		<data>
		AAAFoAAAAyoAAAAB
		</data>
		<data>
		AAAFAAAAAtAAAAAB
		</data>
		<data>
		AAAEgAAAAogAAAAB
		</data>
		<data>
		AAAEAAAAAkAAAAAB
		</data>
		<data>
		AAADSAAAAdQAAAAB
		</data>
		<data>
		AAADIAAAAcIAAAAB
		</data>
		<data>
		AAACgAAAAWgAAAAB
		</data>
		<data>
		AAAPAAAACHAAAAAJAKAAAA==
		</data>
		<data>
		AAANIAAAB2IAAAAJAKAAAA==
		</data>
		<data>
		AAALQAAABlQAAAAJAKAAAA==
		</data>
		<data>
		AAAKAAAABaAAAAAJAKAAAA==
		</data>
		<data>
		AAAIAAAABIAAAAAJAKAAAA==
		</data>
		<data>
		AAAHgAAABDgAAAAJAKAAAA==
		</data>
		<data>
		AAAFAAAAAtAAAAAJAKAAAA==
		</data>
	</array>
	<key>target-default-ppmm</key>
	<real>10.069930100000001</real>
</dict>
</plist>
```

**Comment by gorda** [comment]
# 最终的最简单的解决方法

基于 hackintool 可用的文件对比测试后，发现与文件内容无关。

只需要将生成的文件 `isplayProductID-00` 重命名为  `isplayProductID-0` 就可以了


# 为不太清楚命令行的朋友准备的

- 不懂的命令行朋友在按照 `正常流程执行脚本之后`，执行下面这一条命令：

`cd /System/Library/Displays/Contents/Resources/Overrides/DisplayVendorID-2163   && sudo mv DisplayProductID-00  DisplayProductID-0`

> VerndorID-XXXX 后面的四位数以你的显示器为准

- 如果执行脚本时，还选择了 `修改显示器 ICON`，还需要执行这条命令：

`sudo mv DisplayProductID-00.icns  DisplayProductID-0.icns`

- 然后重启即可

> 该方法在我的 10.15.1 系统上有效

**Comment by zhantaojava** [comment]
> # 最终的最简单的解决方法
> 基于 hackintool 可用的文件对比测试后，发现与文件内容无关。
> 
> 只需要将生成的文件 `isplayProductID-00` 重命名为 `isplayProductID-0` 就可以了
> 
> # 为不太清楚命令行的朋友准备的
> * 不懂的命令行朋友在按照 `正常流程执行脚本之后`，执行下面这一条命令：
> 
> `cd /System/Library/Displays/Contents/Resources/Overrides/DisplayVendorID-2163 && sudo mv DisplayProductID-00 DisplayProductID-0`
> 
> > VerndorID-XXXX 后面的四位数以你的显示器为准
> 
> * 如果执行脚本时，还选择了 `修改显示器 ICON`，还需要执行这条命令：
> 
> `sudo mv DisplayProductID-00.icns DisplayProductID-0.icns`
> 
> * 然后重启即可
> 
> > 该方法在我的 10.15.1 系统上有效

我的DisplayProductID 不是00结尾的， DisplayProductID-f1c 怎么改？

**Comment by zhantaojava** [comment]
> # 最终的最简单的解决方法
> 基于 hackintool 可用的文件对比测试后，发现与文件内容无关。
> 
> 只需要将生成的文件 `isplayProductID-00` 重命名为 `isplayProductID-0` 就可以了
> 
> # 为不太清楚命令行的朋友准备的
> * 不懂的命令行朋友在按照 `正常流程执行脚本之后`，执行下面这一条命令：
> 
> `cd /System/Library/Displays/Contents/Resources/Overrides/DisplayVendorID-2163 && sudo mv DisplayProductID-00 DisplayProductID-0`
> 
> > VerndorID-XXXX 后面的四位数以你的显示器为准
> 
> * 如果执行脚本时，还选择了 `修改显示器 ICON`，还需要执行这条命令：
> 
> `sudo mv DisplayProductID-00.icns DisplayProductID-0.icns`
> 
> * 然后重启即可
> 
> > 该方法在我的 10.15.1 系统上有效
@gorda 
我的ProductID 是 DisplayProductID-f1c    该怎么改？

**Comment by gorda** [comment]
> 我的ProductID 是 DisplayProductID-f1c    该怎么改？

把上面命令中的 `2163` 改成你自己的 `f1c` 就可以了

**Comment by zhantaojava** [comment]
我用hackintool  生成的文件夹名字是 DisplayVendorID-4c2d,  里面的文件是DisplayProductID-f1c。 你提到的
> >cd /System/Library/Displays/Contents/Resources/Overrides/DisplayVendorID-2163 && sudo mv DisplayProductID-00 DisplayProductID-0
这个命令， 是修改ProductID这个文件吧？ 我的那个文件没有你说的-00这样的名字诶。
