### ISSUE TITLE
2K显示器无法修改文字大小

### ISSUE THREAD

**Issue by Chillimeat** [xzhih/one-key-hidpi#95]
你好命令执行成功之后，在系统配置中显示的：
![image](https://user-images.githubusercontent.com/24307825/69009504-acf68880-0990-11ea-97c1-80ad6af925db.png)
无法选择文字大小，但是选择1920 1080确实清楚了很多。

**Comment by zhanghan3** [comment]
最后怎么解决的呢，我这里也是不能缩放，只有改分辨率的选项
