### ISSUE TITLE
你好，睡眠唤醒时屏幕缩小的问题依然存在？

### ISSUE THREAD

**Issue by VincentCheungCW** [xzhih/one-key-hidpi#96]
你好，机器配置：XPS 9360 i5 8代CPU，1080P，macos Catalina
安装时选择了（修复睡眠唤醒屏幕缩小）的选项，但使用过程中依然出现了该问题：抬起盖子唤醒时屏幕缩小到左上角大概1/4，关闭盖子再次打开就恢复正常，每次都是如此。
请问如何解决呀？谢谢

**Comment by xzhih** [comment]
这就没办法了，我暂时没有其他的方法解决这个问题，建议你去搜索看看其他人是怎么解决的，如果可行我就合并到脚本里
