### ISSUE TITLE
我买DELL U2718Q 4k屏幕接上去也是字体模糊锯齿，是要开启hidpi么？

### ISSUE THREAD

**Issue by mengdu** [xzhih/one-key-hidpi#98]
目前我啥都没做，可以开启1920*1080的分辨率，但是字体太大了，改其他分辨率字体都不太理想，模糊。
![image](https://user-images.githubusercontent.com/11366654/69244896-d574c180-0be0-11ea-8128-a107e346bc4d.png)

电脑是2019 款的mbp。
请问，我这个是要开启hidpi么？

**Comment by telepati** [comment]
No need. All resolutions in the picture you sent are HDPI.

**Comment by mengdu** [comment]
但是我切换其他分辨率，展示效果都很差呢，这个是什么原因？

**Comment by xzhih** [comment]
正常情况下系统识别 4K 显示器后会有缩放调节选项，不需要这个脚本，也非常不建议用
你可以尝试注入 EDID 让系统识别，或者检查一下连接的接口和线材是否支持 4K@60

如果是黑苹果，你最好检查一下显卡驱动，如果用的核显，可以打缓冲帧补丁

以上都不行，就可以使用这个脚本，选择自定义分辨率，输入一下你想要的分辨率档位

如：
 
```
2560x1440 2048x1152 1920x1080
```

**Comment by xzhih** [comment]
以上是给有相同问题的人的回答

而你是 MBP，我就建议你看一下你的拓展坞或者转换线等是否合适了，都有这么好的设备了，买个贝尔金吧

**Comment by mengdu** [comment]
感谢回答，不知道是不是线的问题，我用的是type-c - miniDP 的线，直连的，我总感觉显示字体有锯齿。

**Comment by wangqingzh** [comment]
> 感谢回答，不知道是不是线的问题，我用的是type-c - miniDP 的线，直连的，我总感觉显示字体有锯齿。

我黑苹果接的 hdmi dell 4k 之前用的核显 换了rx5500xt后 明显的锯齿感不知道为什么 win10 上也是这样
我打算买一个 dp 线
