### ISSUE TITLE
NightShift在开启HiDPI后无法使用

### ISSUE THREAD

**Issue by xuyoji** [xzhih/one-key-hidpi#99]
显示器：BenQ PD3200Q 2k分辨率
显卡：UHD 630
系统：10.15.1 hackintosh
问题描述：一开始使用脚本时可以开启HiDPI，但是可用HiDPI的分辨率很低。尝试clover加入引导参数lilucpu=9后解决该问题，但是开启后系统选项中NightShift选项卡消失。去掉lilucpu=9，或者关闭HiDPI都可以使得该选项卡恢复。在另外的Dell1080p显示器上HiDPI和NIghtShift均工作正常。

**Comment by xzhih** [comment]
你黑苹果的问题，我这里不负责解决
